### DISCUSSION TITLE
RocketChat keeps loading non-stop

### DISCUSSION THREAD

**Discussion by JohnStroe** [RocketChat/Rocket.Chat#30861] [Q&A]
I have recently had to reinstall Debian on my server. I have a Dell R720, with an Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz, 64 GB of ram and about 10 TB of storage on 6 separate HardDisks (which, each 2 are set in a raid 1 configuration), with the system being installed on a Samsung SSD (512 GB). After reinstalling Debian and solving some issues with ssh connectivity I tried to reinstall RocketChat, as I've had it in the past too. I used the compose.yml example that was given word by word, except changed the location where MongoDB saves its data.
Instead of:
```
mongodb:
    image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-5.0}
    restart: always
    volumes:
      - mongodb_data:/bitnami/mongodb
```
I wrote:
```
mongodb:
    image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-5.0}
    restart: always
    volumes:
      - /home/webadmin/rc_storage:/bitnami/mongoldb
```
And deleted the following lines:
```
volumes:
  mongodb_data: { driver: local }
```

And then gave mongodb read/write access to that file.

The issue is that after installing RocketChat 6.4.5 and booting it up, when I went to go to http://serverip:3000, I was presented with a loading screen, that has been loading for the past 2 days (I haven't had time to post this when the issue appeared) with the following error in the console of the web browser: Failed to load resource: Could not connect to the server. http://localhost:3000/__meteor__/dynamic-import/fetch

The file that is specified only contains one line which reads: method GET not allowed

I tried checking the docker image logs and it only says that rocket chat is running without problem, monogdb the same.

After that I tried installing an earlier version ( 6.2.6 ) as I have used it before and it worked flawlessly.

When I did that. The following error appeared in the RocketChat docker image logs: 
`{"level":40,"time":"2023-11-03T18:37:53.470Z","pid":1,"hostname":"e9a1c3162bda","name":"Migrations","msg":"Not migrating, control is locked. Attempt 21/30. Trying again in 10 seconds."}`

As you may see it was attempt 21/30, so it was doing it for a while.

After that I tried to use the default path for mongodb, but that didn't work either, throwing the same errors in both cases (RocketChat 6.2.6 and RocketChat 6.4.4). And I have also tried using MongoDB 6.0, which again trowed the same errors.

Mention: Before formatting the whole server I decided to upgrade rocket chat from version 6.2.6 to 6.4.4 and it had no problem. It was running perfectly. The only difference is that the files were saved in the default directory.
