### ISSUE TITLE
Permissions error with FileSystem on Docker: "LocalStore: cannot set store permissions 0744"

### ISSUE THREAD

**Issue by flayks** [RocketChat/Rocket.Chat#10231]
### Description:

I'm trying to migrate my Rocket.chat server from a Debian Stretch manual install to a Docker container, and get this error when using FileSystem (I was on GridFS by default but want to switch to FS due to a large MongoDB database size):
>LocalStore: cannot set store permissions 0744 (EPERM: operation not permitted, chmod '/app/uploads')

This is my `docker-compose.yml`:
```yml
version: "3.6"
services:
  rocketchat:
    container_name: tool-rocketchat
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./tmp:/tmp
    environment:
      PORT: 3000
      ROOT_URL: http://se.rv.er.ip:3001
      MONGO_URL: mongodb://mongodb:27017/test-rocketchat
    networks:
      db-mongo:

networks:
  db-mongo:
    external:
      name: db-mongo
```

On the admin the FileSystem path is set to `/app/uploads` so it should work.
I tried different things but nothing actually works, even a clean and fresh install of Rocket.Chat with no database entries.
Any help appreciated, I clearly don't understand the issue here
🙏

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Debian 9.4
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog: No
* Node Version: The Docker latest image node version
* mongoDB Version: 3.6
