### ISSUE TITLE
Desktop app woking, web app not.

### ISSUE THREAD

**Issue by honzasram** [RocketChat/Rocket.Chat#10248]
### Description:

As per title, I've met problem with latest image after recreating whole setup. Web applications is not responding. Proxy response is 504 Gateway Time-out. Same when i try go directly to server.
Desktop app is working like a charm. 

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.2
* Operating System: Debian jessie
* Deployment Method(snap/docker/tar/etc): docker
* Number of Running Instances: 1
* DB Replicaset Oplog: enabled
* Node Version: 
* mongoDB Version: 

Our setup has NGINX reverse proxy with these lines in config:
```
  location /rocket{
    proxy_pass http://machine-ip:3000;
  }
```

docker compose have this:
```
  rocketchat:
    image: rocket.chat:latest
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=https://our.domain.com/rocket
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - Accounts_UseDNSDomainCheck=false
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
     - ./data/runtime/db:/data/db
     - ./data/dump:/dump
    command: mongod --smallfiles --replSet rs0
    labels:
      - "traefik.enable=false"
```
### Relevant logs:

docker logs show this:

```
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: url must be a relative URL:
```
