### ISSUE TITLE
Data persistance

### ISSUE THREAD

**Issue by royalaid** [RocketChat/Rocket.Chat#1042]
As currently stands the default setup for the mongodb docker image relies on storing the journal within the container. This method of storing data for a database is generally frowned upon because all backend data gets wiped when I remove the container. A simple solution would be to provide a default setup using docker's builtin volumes mechanism by adding:
```yml
mongodb:
    image: mongo
    ports:
        - 27017
    volumes:
        - /data/db
```
to the docker-compose.yml or a similar statement to the Dockerfile. By doing moving mongodb's storage location to the host a update can be applied by simply running 
```bash
docker-compose stop && docker-compose rm
docker-compose pull && docker-compose up
```
