### ISSUE TITLE
Help Rocket.Chat

### ISSUE THREAD

**Issue by lasiiee** [RocketChat/Rocket.Chat#10738]
What is the node process? It use 100% of process resourses in our organization. Because of this Rocket.Chat is defolted. (works slowly or not work)

![photo_2018-05-11_11-07-04](https://user-images.githubusercontent.com/39184941/39913698-82016c98-550b-11e8-9141-11a52210ead9.jpg)

**Comment by ph1p** [comment]
We have had the same problem at our company. 
Now we're running it in two docker containers and everything is fine.

**Our docker-compose file:**
```
services:
  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
     - /home/USER/mongo/configdb:/data/configdb
     - /home/USER/mongo/db:/data/db
    command: mongod --smallfiles
    labels:
      - "traefik.enable=false"
    ports:
      - 27017:27017

  rocketchat:
    image: rocketchat/rocket.chat:0.64.1
    restart: unless-stopped
    volumes:
      - /home/USER/uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://chat:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MAIL_URL=
    depends_on:
      - mongo
    ports:
      - 3000:3000
```
