### ISSUE TITLE
White main page - no content - docker-compose under AWS ALB

### ISSUE THREAD

**Issue by brettswift** [RocketChat/Rocket.Chat#11219]
### Description:

Some people have raised issues on black pages under mobile but I'm seeing empty content under an AWS ALB.    I'm running docker compose,  forwarding the docker port 3000 to the host port 80, and then the ALB  terminates SSL and forwards to the host port 80. 

This is as simple as I can make it, everything on one image.   The console when I start rocket chat tells me that it's up and running.   But still I just get a white page. 

```
rocketchat_1  | ➔ System ➔ startup
rocketchat_1  | ➔ +------------------------------------------------------------------------------+
rocketchat_1  | ➔ |                                SERVER RUNNING                                |
rocketchat_1  | ➔ +------------------------------------------------------------------------------+
rocketchat_1  | ➔ |                                                                              |
rocketchat_1  | ➔ |  Rocket.Chat Version: 0.65.2                                                 |
rocketchat_1  | ➔ |       NodeJS Version: 8.9.3 - x64                                            |
rocketchat_1  | ➔ |             Platform: linux                                                  |
rocketchat_1  | ➔ |         Process Port: 3000                                                   |
rocketchat_1  | ➔ |             Site URL: https://obfuscated |
rocketchat_1  | ➔ |     ReplicaSet OpLog: Disabled                                               |
rocketchat_1  | ➔ |          Commit Hash: 706a528708                                             |
rocketchat_1  | ➔ |        Commit Branch: HEAD                                                   |
rocketchat_1  | ➔ |                                                                              |
rocketchat_1  | ➔ +------------------------------------------------------------------------------+
```

### Server Setup Information:
I should note that if I expose the instance port, and hit the IP directly the site works.  It just doesn't work behind an ALB.  I've even opened up all ports from the ALB to the instance.  

- Version of Rocket.Chat Server:  0.65.2
- Operating System: docker rocket.chat image
- Deployment Method: docker
- Number of Running Instances: 1
### Additional context

```
db:
    image: mongo:3.0
    command: mongod --smallfiles

rocketchat:
    image: rocketchat/rocket.chat
    links:
        - db:mongo
    ports:
        - 80:3000
#    environment:
#       - ROOT_URL=https://${ROOT_URL}
redis:
  image: redis
  ports:
    - "6379"
```
