### ISSUE TITLE
Broadcast Connected Instances - Incorrect setting

### ISSUE THREAD

**Issue by rmjstn** [RocketChat/Rocket.Chat#13126]
Hi,

### Description:

We are running a multi-instances of Rocket.Chat.
INSTANCE_IP and extra_hosts are set in the Docker Compose file.
Through tcpdump we see traffic between the two servers (port 3000, in the both ways).

Extract of one Docker Compose file : 

```
rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://rocketchat:toto@mongo34501:27017,mongo34502:27017,mongo34503:27017/rocketchat?authSource=admin&replicaSet=rs01&readPreference=nearest&w=majority
    - MONGO_OPLOG_URL=mongodb://oplog:toto@mongo34501:27017,mongo34502:27017,mongo34503:27017/local?authSource=admin&replicaSet=rs01
    - ROOT_URL=https://rocket.sib.fr
    - PORT=3000
    - INSTANCE_IP=10.241.1.4
  ports:
    - 3000:3000
  extra_hosts:
    - "rocket-1:10.241.1.4"    
    - "rocket-2:10.241.1.7"   
``` 

Notifications and users status doesn’t work properly. As you can see on the screenshots below, in the “Broadcast Connected Instances” section “Auth” and “Current Status > Connected” are not set, and "“Current Status > Status” is set to waiting.

Docker 1 : 
![image](https://user-images.githubusercontent.com/24813225/51027521-64f91f00-1591-11e9-9298-50ec6a2d01a1.png)

Docker 2 : 
![image](https://user-images.githubusercontent.com/24813225/51027578-8b1ebf00-1591-11e9-9ff5-9e29b3bf8b05.png)

In the Docker logs we have : 

Docker 1 :
```
StreamBroadcast ? info startStreamBroadcast
StreamBroadcast ? Auth.info prevent self connect 10.241.1.4:3000
StreamBroadcast ? Connection.info connecting in 10.241.1.7:3000
StreamBroadcast ? Auth.info prevent self connect 10.241.1.4:3000
```
Docker 2 :
```
StreamBroadcast ? info startStreamBroadcast
StreamBroadcast ? Auth.info prevent self connect 10.241.1.7:3000
StreamBroadcast ? Connection.info connecting in 10.241.1.4:3000
StreamBroadcast ? Auth.info prevent self connect 10.241.1.7:3000
```

### Server Setup Information:

- Version of Rocket.Chat Server: 0.73.2
- Operating System: Debian GNU/Linux 9
- Deployment Method: Docker
- Number of Running Instances: 2
- DB Replicaset Oplog: enabled
- NodeJS Version: 8.11.3 - x64 
- MongoDB Version: 3.4.5

### Additional context

We initially had a mono-instance installation. We export and import the database in a new cluster.
Furthermore, file upload is extremly slow.

### Relevant logs:

We have these MongoDB errors, but I don’t think these are related to the problem :

```
Error in oplog callback TypeError: Cannot read property '_hidden' of undefined
Error in oplog callback TypeError: Cannot read property 'u' of undefined
```

Thanks,

Rémy

**Comment by rmjstn** [comment]
Hi,

I performed an installation from scratch and have the same problem. I found this in the logs : 

First Docker container : 
```
stream error Can't establish a connection to the server at ws://10.241.1.9:3000/websocket
```

Second one : 
```
stream error Can't establish a connection to the server at ws://10.241.1.7:3000/websocket
```

Informations on start up :
```
Rocket.Chat Version: 0.74.0                       
NodeJS Version: 8.11.4 - x64                 
Platform: linux                        
Process Port: 3000                         
Site URL: https://rocket-test.xxx.xx/  
ReplicaSet OpLog: Enabled                      
Commit Hash: cc5391e58c                   
Commit Branch: HEAD       
```                  
 
From the first container, I can join the second one on port 3000 :
```
rocketchat@865f8ce4ac9b:/app/bundle$ > /dev/tcp/10.241.1.9/3000
```
I see network packets on the second server.

I've installed [wscat](https://github.com/websockets/wscat) in the container. It works, I can open the websocket :

```
> rocketchat@865f8ce4ac9b:/app/bundle$ wscat -c ws://10.241.1.9:3000/websocket
connected (press CTRL+C to quit)
< {"server_id":"0"}
```

When I start the container on the first server, I don't see any network packets on port 3000 on the second one.

One of the Docker Compose file : 
```
rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://rocketchat:toto@mongo345:27017/rocketchat?authSource=admin&replicaSet=rs01&readPreference=nearest&w=majority
    - MONGO_OPLOG_URL=mongodb://oplog:toto@mongo345:27017/local?authSource=admin&replicaSet=rs01
    - ROOT_URL=https://rocket-test.xxxxx.xx
    - PORT=3000
    - INSTANCE_IP=10.241.1.7
  ports:
    - 3000:3000
  extra_hosts:
    - "rocket-1:10.241.1.7"    
    - "rocket-2:10.241.1.9"    
```

In summary : 

1.  From container1, check open port : packets capture on server 2.
2.  From container 1, call websocket on container 2 (via wscat) : packets capture on server 2.
3. Start container 1, error on websocket connection : NO packets capture on server 2.

Thanks,

Rémy
