### ISSUE TITLE
Exception in onLogin callback: TypeError: Cannot redefine property: loginAt

### ISSUE THREAD

**Issue by bellini666** [RocketChat/Rocket.Chat#13488]
Just noted this on my setup. It's brand new using docker-compose:

```
rocketchat_1  | Exception in onLogin callback: TypeError: Cannot redefine property: loginAt
rocketchat_1  |     at Function.defineProperty (<anonymous>)
rocketchat_1  |     at Object.keys.forEach.p (packages/rocketchat:statistics/server/lib/SAUMonitor.js:279:12)
rocketchat_1  |     at Array.forEach (<anonymous>)
rocketchat_1  |     at SAUMonitorClass._updateConnectionInfo (packages/rocketchat:statistics/server/lib/SAUMonitor.js:278:22)
rocketchat_1  |     at Accounts.onLogin.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:120:9)
rocketchat_1  |     at packages/callback-hook/hook.js:130:22
rocketchat_1  |     at _onLoginHook.each.callback (packages/accounts-base/accounts_server.js:178:7)
rocketchat_1  |     at Hook.each (packages/callback-hook/hook.js:108:15)
rocketchat_1  |     at AccountsServer._successfulLogin (packages/accounts-base/accounts_server.js:177:23)
rocketchat_1  |     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:350:12)
rocketchat_1  |     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)
rocketchat_1  |     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
rocketchat_1  |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
rocketchat_1  |     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
rocketchat_1  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
rocketchat_1  |     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
rocketchat_1  |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
rocketchat_1  |     at Promise (packages/ddp-server/livedata_server.js:715:46)
rocketchat_1  |     at new Promise (<anonymous>)
rocketchat_1  |     at Session.method (packages/ddp-server/livedata_server.js:689:23)
rocketchat_1  |     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by robinreinhardt** [comment]
I have the same issue.

* Version of Rocket.Chat Server: 0.74.2

* Operating System: CentOS 7.6

* Number of Running Instances: 4

* MongoDB Version: 3.6.9

**Comment by gabrielloberg** [comment]
Same issue here, but after upgrading from 0.70.4 on a manual install.

Version of Rocket.Chat Server: 0.74.3
Operating System: Debian 9.8
Number of Running Instances: 3
MongoDB Version: 3.2.11

**Comment by MatthiasHertel** [comment]
same issue here after a fresh install with docker-compose. i skipped the setup wizard with ` - OVERWRITE_SETTING_Show_Setup_Wizard=completed` is that a problem ?

below some informations:

**docker-compose.yml**
```
version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    command: bash -c 'for i in `seq 1 30`; do node main.js && s=$$? && break || s=$$?; echo "Tried $$i times. Waiting 5 secs..."; sleep 5; done; (exit $$s)'
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=https://www.XXXXXXXXX.net
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=XXXXXXXXXXXX
      - ADMIN_EMAIL=admin@example.com
      - OVERWRITE_SETTING_Show_Setup_Wizard=completed
      - MAIL_URL=smtp://smtp.email
#       - HTTP_PROXY=http://proxy.domain.com
#       - HTTPS_PROXY=http://proxy.domain.com
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo:4.0
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
     #- ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:4.0
    command: 'bash -c "for i in `seq 1 30`; do mongo mongo/rocketchat --eval \"rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})\" && s=$$? && break || s=$$?; echo \"Tried $$i times. Waiting 5 secs...\"; sleep 5; done; (exit $$s)"'
    depends_on:
      - mongo

```

**logs**
```
rocketchat_1          | Exception in onLogin callback: TypeError: Cannot redefine property: loginAt
rocketchat_1          |     at Function.defineProperty (<anonymous>)
rocketchat_1          |     at Object.keys.forEach.p (packages/rocketchat:statistics/server/lib/SAUMonitor.js:279:12)
rocketchat_1          |     at Array.forEach (<anonymous>)
rocketchat_1          |     at SAUMonitorClass._updateConnectionInfo (packages/rocketchat:statistics/server/lib/SAUMonitor.js:278:22)
rocketchat_1          |     at Accounts.onLogin.info (packages/rocketchat:statistics/server/lib/SAUMonitor.js:120:9)
rocketchat_1          |     at packages/callback-hook/hook.js:130:22
rocketchat_1          |     at _onLoginHook.each.callback (packages/accounts-base/accounts_server.js:178:7)
rocketchat_1          |     at Hook.each (packages/callback-hook/hook.js:108:15)
rocketchat_1          |     at AccountsServer._successfulLogin (packages/accounts-base/accounts_server.js:177:23)
rocketchat_1          |     at AccountsServer._attemptLogin (packages/accounts-base/accounts_server.js:350:12)
rocketchat_1          |     at MethodInvocation.methods.login (packages/accounts-base/accounts_server.js:520:23)
rocketchat_1          |     at MethodInvocation.methodMap.(anonymous function) (packages/rocketchat_monitoring.js:2731:30)
rocketchat_1          |     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
rocketchat_1          |     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
rocketchat_1          |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
rocketchat_1          |     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
rocketchat_1          |     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
rocketchat_1          |     at Promise (packages/ddp-server/livedata_server.js:715:46)
rocketchat_1          |     at new Promise (<anonymous>)
rocketchat_1          |     at Session.method (packages/ddp-server/livedata_server.js:689:23)
rocketchat_1          |     at packages/ddp-server/livedata_server.js:559:43
```
