### ISSUE TITLE
how to configure openldap ldaps:// on Rocket.Chat

### ISSUE THREAD

**Issue by icode** [RocketChat/Rocket.Chat#1363]
my config
```json
{"filter": "(&(objectClass=*)(|(mail=#{username})(uid=#{username})))","scope": "sub","userDN": "uid=admin,ou=people,dc=sinitek-corp,dc=com", "password": "password"}
```

and my gitlab config
```yaml
main: # 'main' is the GitLab 'provider ID' of this LDAP server
     label: 'LDAP'
     host: 'ldap.sinitek-corp.com'
     port: 636
     uid: 'uid'
     method: 'ssl' # "tls" or "ssl" or "plain"
     bind_dn: 'uid=admin,ou=people,dc=sinitek-corp,dc=com'
     password: 'passwpord'
     active_directory: true
     allow_username_or_email_login: true
     block_auto_created_users: false
     base: 'ou=people,dc=sinitek-corp,dc=com'
     user_filter: ''
     ## EE only
     group_base: 'ou=groups,dc=sinitek-corp,dc=com'
     admin_group: 'cn=admin'
     sync_ssh_keys: false

```

but i can't login with ldaps
