### ISSUE TITLE
RocketChat server crashes shortly after startup

### ISSUE THREAD

**Issue by ference** [RocketChat/Rocket.Chat#14093]
### Description:

The following error occurs just after the RocketChat container is started in a [docker-compose setup](https://rocket.chat/docs/installation/docker-containers/docker-compose/):

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
```
Here is the container log leading up to the crash with rust backtrace enabled:
```
rocketchat_1  | Using GridFS for custom sounds storage
rocketchat_1  | Using GridFS for custom emoji storage
rocketchat_1  | Loaded the Apps Framework and loaded a total of 0 Apps!
rocketchat_1  | ➔ System ➔ startup
rocketchat_1  | ➔ +----------------------------------------------+
rocketchat_1  | ➔ |                SERVER RUNNING                |
rocketchat_1  | ➔ +----------------------------------------------+
rocketchat_1  | ➔ |                                              |
rocketchat_1  | ➔ |  Rocket.Chat Version: 0.74.3                 |
rocketchat_1  | ➔ |       NodeJS Version: 8.11.4 - x64           |
rocketchat_1  | ➔ |             Platform: linux                  |
rocketchat_1  | ➔ |         Process Port: 3000                   |
rocketchat_1  | ➔ |             Site URL: https://example.com    |
rocketchat_1  | ➔ |     ReplicaSet OpLog: Disabled               |
rocketchat_1  | ➔ |          Commit Hash: 202a465f1c             |
rocketchat_1  | ➔ |        Commit Branch: HEAD                   |
rocketchat_1  | ➔ |                                              |
rocketchat_1  | ➔ +----------------------------------------------+
rocketchat_1  | thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
rocketchat_1  | stack backtrace:
rocketchat_1  |    0: <unknown>
rocketchat_1  |    1: <unknown>
rocketchat_1  |    2: <unknown>
rocketchat_1  |    3: <unknown>
rocketchat_1  |    4: <unknown>
rocketchat_1  |    5: <unknown>
rocketchat_1  |    6: <unknown>
rocketchat_1  |    7: <unknown>
rocketchat_1  |    8: <unknown>
rocketchat_1  |    9: <unknown>
rocketchat_1 exited with code 139
```

### Steps to reproduce:

Unfortunately there was no obvious event leading to this failure. The issue started occurring even though there was no recent config change.

### Server Setup Information:

- Version of Rocket.Chat Server: 0.74.3
- Operating System: Ubuntu Xenial
- Deployment Method: docker-compose
- Number of Running Instances: 1
- DB Replicaset Oplog: 
- NodeJS Version: 8.11.4 - x64
- MongoDB Version: 4.0.4

### Additional context

The container used to run stable without any issues for weeks. I tried stopping and removing containers and recreating them, but the problem persists.

**Comment by geekgonecrazy** [comment]
That commit doesn't match 0.74.3  what custom changes have you made?

**Comment by ference** [comment]
I were no custom changes apart from picking configuration options in the admin panel.

This is my docker-compose.yml:
```
db:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles
  restart: always

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://example.com
    - Accounts_UseDNSDomainCheck=True
    - RUST_BACKTRACE=1
  links:
    - db:db
  ports:
    - 127.0.0.1:3001:3000
  restart: always

hubot:
  image: rocketchat/hubot-rocketchat:latest
  environment:
    - ROCKETCHAT_URL=192.168.1.22:3001
    - ROCKETCHAT_ROOM=GENERAL
    - ROCKETCHAT_USER=User
    - ROCKETCHAT_PASSWORD=Secret
    - BOT_NAME=TheBot
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3002:8080
  restart: always
```

Initially I ran an older version, but a few weeks ago upgrade using the following steps:

```
docker pull rocketchat/rocket.chat:latest
docker-compose stop rocketchat
docker-compose rm rocketchat
docker-compose up -d rocketchat
```
