### ISSUE TITLE
Container startup fails on Openshift

### ISSUE THREAD

**Issue by SS-TT** [RocketChat/Rocket.Chat#14670]
### Description:

Container startup fails with an error related to Mongo's OpLog.
Mongo's instance is the one provided with RocketChat's template, so I'd expect OpLog to be enabled.

Enabling OpLog will force me to restart the pod, losing its updated configuration.

### Steps to reproduce:

Everything in this [guide](https://rocket.chat/docs/installation/automation-tools/openshift/).

### Expected behavior:

RocketChat should start correctly.

### Actual behavior:

Container fails to start.

### Server Setup Information:
(everything is in the log below)
- Version of Rocket.Chat Server: 
- Operating System: CentOs
- Deployment Method: Openshift
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version: 
- MongoDB Version: 

### Relevant logs:
```
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
Setting default file store to GridFS
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
{"line":"120","file":"migrations.js","message":"Migrations: Not migrating, already at version 145","time":{"$date":1559116269150},"level":"info"}
ufs: temp directory created at "/tmp/ufs"
Loaded the Apps Framework and loaded a total of 0 Apps!
Updating process.env.MAIL_URL
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
➔ server.js:207 System ➔ error
➔ +---------------------------------------------------------------------------+
➔ |                                SERVER ERROR                               |
➔ +---------------------------------------------------------------------------+
➔ |                                                                           |
➔ |  Rocket.Chat Version: 1.1.0                                               |
➔ |       NodeJS Version: 8.11.4 - x64                                        |
➔ |      MongoDB Version: 3.6.3                                               |
➔ |       MongoDB Engine: unknown                                             |
➔ |             Platform: linux                                               |
➔ |         Process Port: 3000                                                |
➔ |             Site URL: http://localhost:3000                                |
➔ |     ReplicaSet OpLog: Disabled                                            |
➔ |          Commit Hash: 484ee10c2b                                          |
➔ |        Commit Branch: HEAD                                                |
➔ |                                                                           |
➔ |  OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT, MORE INFORMATION AT:  |
➔ |  https://go.rocket.chat/i/oplog-required                                   |
➔ |                                                                           |
➔ +---------------------------------------------------------------------------+
```

**Comment by sshniro** [comment]
You need to configure replica set in the mongo DB. If you are using docker compose use this version.

```
version: '3.6'
services:
  mongo:
    image: mongo:3.2
    entrypoint: mongod --smallfiles
    volumes:
      - ./data:/data/db
      - ./data/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs01

  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo

  rocketchat:
    image: rocket.chat:latest
    restart: unless-stopped
    environment:
      - ROOT_URL=http://localhost
      - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs01
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs01
    depends_on:
      - mongo
    ports:
      - "80:3000"
```
