### ISSUE TITLE
Error when Deploying via Docker on Debian Wheezy

### ISSUE THREAD

**Issue by tholu** [RocketChat/Rocket.Chat#1472]
docker-compose version: 1.5.1
docker version 1.9.1, build a34a1d5
I used the latest ``docker-compose.yml`` from the Github repo here (with adjusted ROOT_URL).

```
mongo:
  image: mongo
# volumes:
#    - ./data/runtime/mongo:/data/mongo
#    - ./data/dump:/dump
  command: mongod --smallfiles --replSet rs0 --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:develop
# volumes:
#    - ./uploads:/app/uploads
  environment:
    - ROOT=3000
    - ROOT_URL=http://yourhost:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
# uncomment and set the line below if you need to support mobile apps
#   - DDP_DEFAULT_CONNECTION_URL=http://yourhost:3000
  links:
    - mongo:mongo
  ports:
    - 3000:3000
```

When doing ``docker-compose up``, I get this:

```
rocketchat_1 |
rocketchat_1 | /app/bundle/programs/server/node_modules/fibers/future.js:278
rocketchat_1 | 						throw(ex);
rocketchat_1 | 						      ^
rocketchat_1 | MongoError: not master
rocketchat_1 |     at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
rocketchat_1 |     at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:790:1)
rocketchat_1 |     at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:635:1)
rocketchat_1 |     at setupUsersCollection (accounts_server.js:1413:9)
rocketchat_1 |     at new AccountsServer (accounts_server.js:49:5)
rocketchat_1 |     at Package (globals_server.js:5:12)
rocketchat_1 |     at /app/bundle/programs/server/packages/accounts-base.js:1814:4
rocketchat_1 |     at /app/bundle/programs/server/packages/accounts-base.js:1825:3
rocketchat_1 |     at /app/bundle/programs/server/boot.js:242:10
rocketchat_1 |     at Array.forEach (native)
rocketchat_1 |     - - - - -
rocketchat_1 |     at Object.toError (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
rocketchat_1 |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1354:26
rocketchat_1 |     at Server.Base._callHandler (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
rocketchat_1 |     at /app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
rocketchat_1 |     at [object Object].MongoReply.parseBody (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
rocketchat_1 |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
rocketchat_1 |     at [object Object].emit (events.js:95:17)
rocketchat_1 |     at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
rocketchat_1 |     at [object Object].emit (events.js:98:17)
rocketchat_1 |     at Socket.<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
```
Any idea what is wrong here?

**Comment by geekgonecrazy** [comment]
@tholu this looks like an issue with mongo maybe not being up.  Can you do `docker ps` and verify that mongo is for sure running?

**Comment by tholu** [comment]
@geekgonecrazy I thought docker-compose takes care of starting up mongo as well. It should be running. Could it be a issue with mongo already running on the host? I thought the docker containers are communicating independently from the host with each other.

**Comment by tholu** [comment]
Regarding deployment with docker, the Wiki seems to be out-of-date as well, at least there are several different guides involving docker with completely different steps:
https://github.com/RocketChat/Rocket.Chat/wiki/Docker-Ubuntu-14.04-%2864-bit%29-VPS-with-Nginx-SSL-and-Hubot
https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-with-Docker
https://github.com/RocketChat/Deploy.to.Cloud/tree/master/GenericLinux

**Comment by tholu** [comment]
The problem seems to be ``--replSet rs0``, without it, it runs.

**Comment by tholu** [comment]
Here is my working docker-compose.yml:

```
mongo:
  image: mongo
# volumes:
#    - ./data/runtime/mongo:/data/mongo
#    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:develop
# volumes:
#    - ./uploads:/app/uploads
  environment:
    - ROOT=3000
    - ROOT_URL=http://chat.domain.com:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
# uncomment and set the line below if you need to support mobile apps
#   - DDP_DEFAULT_CONNECTION_URL=http://chat.domain.com:3000
  links:
    - mongo:mongo
  ports:
    - 3000:3000

hubot:
  image: rocketchat/hubot-rocketchat
  environment:
    - ROCKETCHAT_URL=chat.domain.com:3000
    - ROCKETCHAT_ROOM=GENERAL
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=upheeG2fei4E
    - BOT_NAME=bot
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-pugme,hubot-rules,hubot-shipit,hubot-thesimpsons,hubot-highfive,hubot-boatcat,hubot-table-flip
  links:
    - rocketchat:rocketchat
```
