### ISSUE TITLE
run rocket chat on openshift

### ISSUE THREAD

**Issue by yeganx** [RocketChat/Rocket.Chat#15068]
hi , i have try run rocket chat on openshift , through 2 link
1)https://rocket.chat/docs/installation/automation-tools/openshift/

with this link the rocket chat log is 
`oc logs rocketchat-1-vzmwn`
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
ufs: temp directory created at "/tmp/ufs"
Loaded the Apps Framework and loaded a total of 0 Apps!
Updating process.env.MAIL_URL
Using GridFS for custom sounds storage
Using GridFS for custom emoji storage
➔ server.js:207 System ➔ error
➔ +---------------------------------------------------------------------------+
➔ |                                SERVER ERROR                               |
➔ +---------------------------------------------------------------------------+
➔ |                                                                           |
➔ |  Rocket.Chat Version: 1.2.3                                               |
➔ |       NodeJS Version: 8.11.4 - x64                                        |
➔ |      MongoDB Version: 3.6.3                                               |
➔ |       MongoDB Engine: unknown                                             |
➔ |             Platform: linux                                               |
➔ |         Process Port: 3000                                                |
➔ |             Site URL: http://localhost:3000                               |
➔ |     ReplicaSet OpLog: Disabled                                            |
➔ |          Commit Hash: d3e690ad7f                                          |
➔ |        Commit Branch: HEAD                                                |
➔ |                                                                           |
➔ |  OPLOG / REPLICASET IS REQUIRED TO RUN ROCKET.CHAT, MORE INFORMATION AT:  |
➔ |  https://go.rocket.chat/i/oplog-required                                  |
➔ |                                                                           |
➔ +---------------------------------------------------------------------------+

2)https://rocket.chat/docs/installation/paas-deployments/openshift/
oc decribe pod rocket-chat-cghsajas
```
Events:
  Type     Reason     Age               From                             Message
  ----     ------     ----              ----                             -------
  Normal   Scheduled  3m                default-scheduler                Successfully assigned rocket-chat/rocketchat-2-frqtm to compute2.X.com
  Normal   Pulling    2m (x2 over 3m)   kubelet, compute2.X.com  pulling image "repo.X.com:5000/openshift/rocket.chat@sha256:818900ffba723607c68a6e6a907dab94153f64a987112d7c3500fa4f8d32edab"
  Normal   Pulled     2m (x2 over 3m)   kubelet, compute2.X.com  Successfully pulled image "repo.X.com:5000/openshift/rocket.chat@sha256:818900ffba723607c68a6e6a907dab94153f64a987112d7c3500fa4f8d32edab"
  Normal   Created    2m (x2 over 3m)   kubelet, compute2.X.com  Created container
  Normal   Started    2m (x2 over 3m)   kubelet, compute2.X.com  Started container
  Normal   Killing    2m                kubelet, compute2.X.com  Killing container with id docker://rocketchat:Container failed liveness probe.. Container will be killed and recreated.
  Warning  Unhealthy  1m (x12 over 3m)  kubelet, compute2.Xcom  Readiness probe failed: Get http://10.128.3.209:3000/api/v1/info: dial tcp 10.128.3.209:3000: connect: connection refused
  Warning  Unhealthy  1m (x4 over 3m)   kubelet, compute2.X.com  Liveness probe failed: Get http://10.128.3.209:3000/api/v1/info: dial tcp 10.128.3.209:3000: connect: connection refused
```
oc logs rocket-chat-fhdhsjds
```
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
LocalStore: store created at 
Setting default file store to GridFS
Setting default file store to GridFS
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```
after some try deployment state is
```
oc get pods
NAME                  READY     STATUS    RESTARTS   AGE
mongodb-1-srzb7       1/1       Running   0          40m
rocketchat-1-deploy   0/1       Error     0          30m
rocketchat-2-deploy   0/1       Error     0          13m
```

**Comment by yeganx** [comment]
any help on this issue

**Comment by vvanouytsel** [comment]
See https://github.com/RocketChat/Rocket.Chat/issues/14670
It seems that RocketChat requires MongoDB with a replica set.

We should fix this in the OpenShift templates
https://github.com/RocketChat/Rocket.Chat/tree/develop/.openshift

**Comment by yeganx** [comment]
I see the issue 14670
```
kind: Template
apiVersion: v1
metadata:
  name: mongodb-petset-replication
  annotations:
    description: "MongoDB Replication Example (based on StatefulSet). You must have persistent volumes available in your cluster to use this template."
    iconClass: "icon-mongodb"
    tags: "database,mongodb,replication"
parameters:
  - name: MONGODB_USER
    displayName: "MongoDB Connection Username"
    description: "Username for MongoDB user that will be used for accessing the database."
    generate: expression
    from: "[a-zA-Z0-9]{3}"
    required: true

  - name: MONGODB_PASSWORD
    displayName: "MongoDB Connection Password"
    description: "Password for the MongoDB connection user."
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true

  - name: MONGODB_DATABASE
    displayName: "MongoDB Database Name"
    description: "Name of the MongoDB database accessed."
    value: sampledb
    required: true

  - name: MONGODB_ADMIN_PASSWORD
    displayName: "MongoDB Admin Password"
    description: "Password for the database admin user."
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true

  - name: MONGODB_REPLICA_NAME
    displayName: "Replica Set Name"
    description: "The name of the replica set."
    value: rs0
    required: true

  - name: MONGODB_KEYFILE_VALUE
    displayName: "Keyfile Content"
    description: "The value of the MongoDB keyfile (https://docs.mongodb.com/manual/core/security-internal-authentication/#internal-auth-keyfile)."
    generate: expression
    from: "[a-zA-Z0-9]{255}"
    required: true

  - name: MONGODB_IMAGE
    displayName: "MongoDB Container Image"
    description: "A reference to a supported MongoDB container image."
    value: "centos/mongodb-32-centos7"
    required: true

  - name: MONGODB_SERVICE_NAME
    displayName: "OpenShift Service Name"
    description: "The name of the OpenShift Service exposed for the database."
    value: mongodb
    required: true

  - name: VOLUME_CAPACITY
    displayName: "Volume Capacity"
    description: "Volume space available for data, e.g. 512Mi, 2Gi."
    value: "1Gi"
    required: true

  - name: MEMORY_LIMIT
    displayName: "Memory Limit"
    description: "Maximum amount of memory the container can use."
    value: "512Mi"

objects:
  # A non-headless service which takes pod readiness into consideration
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${MONGODB_SERVICE_NAME}"
    spec:
      # the list of ports that are exposed by this service
      ports:
        - name: mongodb
          port: 27017
      # will route traffic to pods having labels matching this selector
      selector:
        name: "${MONGODB_SERVICE_NAME}"

  # A headless service to create DNS records
  - kind: Service
    apiVersion: v1
    metadata:
      name: "${MONGODB_SERVICE_NAME}-internal"
      annotations:
        service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    spec:
      clusterIP: None
      # the list of ports that are exposed by this service
      ports:
        - name: mongodb
          port: 27017
      # will route traffic to pods having labels matching this selector
      selector:
        name: "${MONGODB_SERVICE_NAME}"

  - kind: StatefulSet
    apiVersion: apps/v1beta1
    metadata:
      name: "${MONGODB_SERVICE_NAME}"
    spec:
      # pets get DNS/hostnames that follow the pattern: ${metadata.name}-NUM.${spec.serviceName}.default.svc.cluster.local
      serviceName: "${MONGODB_SERVICE_NAME}-internal"
      replicas: 3
      # describes the pod that will be created if insufficient replicas are detected
      template:
        metadata:
          # this label will be used for count running pods
          labels:
            name: "${MONGODB_SERVICE_NAME}"
        spec:
          containers:
            - name: mongo-container
              image: "${MONGODB_IMAGE}"
              ports:
                - containerPort: 27017
              args:
                - "run-mongod-pet"
              volumeMounts:
                - name: mongo-data
                  mountPath: "/var/lib/mongodb/data"
              env:
                - name: MONGODB_USER
                  value: "${MONGODB_USER}"
                - name: MONGODB_PASSWORD
                  value: "${MONGODB_PASSWORD}"
                - name: MONGODB_DATABASE
                  value: "${MONGODB_DATABASE}"
                - name: MONGODB_ADMIN_PASSWORD
                  value: "${MONGODB_ADMIN_PASSWORD}"
                - name: MONGODB_REPLICA_NAME
                  value: "${MONGODB_REPLICA_NAME}"
                - name: MONGODB_KEYFILE_VALUE
                  value: "${MONGODB_KEYFILE_VALUE}"
                - name: MONGODB_SERVICE_NAME
                  value: "${MONGODB_SERVICE_NAME}-internal"
              resources:
                limits:
                  memory: "${MEMORY_LIMIT}"
              readinessProbe:
                exec:
                  command:
                    - stat
                    - /tmp/initialized
      volumeClaimTemplates:
        - metadata:
            name: mongo-data
            annotations:
              # Uncomment this if using dynamic volume provisioning.
              # https://docs.okd.io/latest/install_config/persistent_storage/dynamically_provisioning_pvs.html
              # volume.alpha.kubernetes.io/storage-class: anything
          spec:
            # the volume can be mounted as read-write by a single node
            accessModes: [ ReadWriteOnce ]
            resources:
              requests:
                storage: "${VOLUME_CAPACITY}"

```

rocketchat 
```


{
  "kind": "Template",
  "apiVersion": "v1",
  "metadata": {
    "name": "rocket-chat-ephemeral",
    "annotations": {
      "description": "Rocket.Chat with a MongoDB database running with an Ephemeral storage.",
      "tags": "quickstart,nodejs,mongodb,instant-app",
      "iconClass": "icon-nodejs"
    }
  },
  "objects": [
   
    {
      "kind": "DeploymentConfig",
      "apiVersion": "v1",
      "metadata": {
        "name": "rocketchat",
        "creationTimestamp": null,
        "labels": {
          "app": "rocketchat"
        },
        "annotations": {
          "openshift.io/generated-by": "OpenShiftNewApp"
        }
      },
      "spec": {
        "strategy": {
          "type": "Rolling",
          "rollingParams": {
            "updatePeriodSeconds": 1,
            "intervalSeconds": 1,
            "timeoutSeconds": 600,
            "maxUnavailable": "25%",
            "maxSurge": "25%"
          },
          "resources": {
          }
        },
        "triggers": [
          {
            "type": "ConfigChange"
          },
          {
            "type": "ImageChange",
            "imageChangeParams": {
              "automatic": true,
              "containerNames": [
                "rocketchat"
              ],
              "from": {
                "kind": "ImageStreamTag",
                "name": "rocketchat:latest"
              }
            }
          }
        ],
        "replicas": 1,
        "test": false,
        "selector": {
          "app": "rocketchat",
          "deploymentconfig": "rocketchat"
        },
        "template": {
          "metadata": {
            "creationTimestamp": null,
            "labels": {
              "app": "rocketchat",
              "deploymentconfig": "rocketchat"
            },
            "annotations": {
              "openshift.io/container.rocketchat.image.entrypoint": "[\"node\",\"main.js\"]",
              "openshift.io/generated-by": "OpenShiftNewApp"
            }
          },
          "spec": {
            "volumes": [
              {
                "name": "rocketchat-volume-1",
                "emptyDir": {
                }
              }
            ],
            "containers": [
              {
                "name": "rocketchat",
                "image": "${ROCKETCHAT_IMAGE}:latest",
                "ports": [
                  {
                    "containerPort": 3000,
                    "protocol": "TCP"
                  }
                ],
                "env": [
                  {
                    "name": "MONGO_URL",
                    "value": "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}"
                  }
                ],
                "resources": {
                },
                "volumeMounts": [
                  {
                    "name": "rocketchat-volume-1",
                    "mountPath": "/app/uploads"
                  }
                ],
                "readinessProbe": {
                  "httpGet": {
                    "path": "/api/v1/info",
                    "port": 3000,
                    "scheme": "HTTP"
                  },
                  "initialDelaySeconds": 5,
                  "timeoutSeconds": 1,
                  "periodSeconds": 10,
                  "successThreshold": 1,
                  "failureThreshold": 3
                },
                "livenessProbe": {
                  "httpGet": {
                    "path": "/api/v1/info",
                    "port": 3000,
                    "scheme": "HTTP"
                  },
                  "initialDelaySeconds": 30,
                  "timeoutSeconds": 1,
                  "periodSeconds": 10,
                  "successThreshold": 1,
                  "failureThreshold": 3
                },
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "Always"
              }
            ],
            "restartPolicy": "Always",
            "terminationGracePeriodSeconds": 30,
            "dnsPolicy": "ClusterFirst",
            "securityContext": {
            }
          }
        }
      },
      "status": {
      }
    },
    {
      "kind": "Route",
      "apiVersion": "v1",
      "metadata": {
        "name": "rocketchat",
        "creationTimestamp": null,
        "labels": {
          "app": "rocketchat"
        },
        "annotations": {
          "openshift.io/host.generated": "true"
        }
      },
      "spec": {
        "to": {
          "kind": "Service",
          "name": "rocketchat"
        },
        "port": {
          "targetPort": "3000-tcp"
        }
      },
      "status": {
        "ingress": null
      }
    },
    {
      "kind": "Service",
      "apiVersion": "v1",
      "metadata": {
        "name": "rocketchat",
        "creationTimestamp": null,
        "labels": {
          "app": "rocketchat"
        },
        "annotations": {
          "openshift.io/generated-by": "OpenShiftNewApp"
        }
      },
      "spec": {
        "ports": [
          {
            "name": "3000-tcp",
            "protocol": "TCP",
            "port": 3000,
            "targetPort": 3000
          }
        ],
        "selector": {
          "app": "rocketchat",
          "deploymentconfig": "rocketchat"
        },
        "type": "ClusterIP",
        "sessionAffinity": "None"
      },
      "status": {
        "loadBalancer": {
        }
      }
    }
  ],
  "parameters": [
    {
      "name": "MEMORY_LIMIT",
      "displayName": "Memory Limit",
      "description": "Maximum amount of memory the container can use.",
      "value": "512Mi"
    },
    {
      "name": "DATABASE_SERVICE_NAME",
      "displayName": "Database Service Name",
      "description": "The name of the OpenShift Service exposed for the database.",
      "value": "mongodb",
      "required": true
    },
    {
      "name": "MONGODB_USER",
      "displayName": "MongoDB User",
      "description": "Username for MongoDB user that will be used for accessing the database.",
      "generate": "expression",
      "from": "user[A-Z0-9]{3}",
      "required": true
    },
    {
      "name": "MONGODB_PASSWORD",
      "displayName": "MongoDB Password",
      "description": "Password for the MongoDB user.",
      "generate": "expression",
      "from": "[a-zA-Z0-9]{16}",
      "required": true
    },
    {
      "name": "MONGODB_DATABASE",
      "displayName": "MongoDB Database Name",
      "description": "Name of the MongoDB database accessed.",
      "value": "rocketchatdb",
      "required": true
    },
    {
      "name": "ROCKETCHAT_IMAGE",
      "displayName": "RocketChat Image",
      "description": "The RocketChat image to use for this deployment",
      "required": true,
      "value": "rocketchat/rocket.chat"
    },
    {
      "name": "MONGODB_ADMIN_PASSWORD",
      "displayName": "MongoDB Admin Password",
      "description": "Password for the database admin user.",
      "generate": "expression",
      "from": "[a-zA-Z0-9]{16}",
      "required": true
    }
  ]
}
```

and on master node's mongo shell to grant user access to local db.
```

mongo -u admin -p ${MONGODB_ADMIN_PASSWORD} admin
use rocketchatdb
db.grantRolesToUser("$MONGODB_USER", [ "readWrite" , { role: "readWrite", db: "local" } ])

```
the is set hese environment variables to rocket.chat deployment:
```
MONGO_URL=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/${MONGODB_DATABASE}?replicaSet=${MONGODB_REPLICA_NAME}

MONGO_URL_OPLOG_URL=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/local?authSource=${MONGODB_DATABASE}?replicaSet=${MONGODB_REPLICA_NAME}

```
after alllll this 
```
rocket-chat pod error 

/app/bundle/programs/server/node_modules/fibers/future.js:313
--

I set replicasetname to mongodb 
where is wrong
