### ISSUE TITLE
Deployment via Docker containers fails using a custom MongoDB port

### ISSUE THREAD

**Issue by luav** [RocketChat/Rocket.Chat#15241]
### Description:

Rocket Chat deployment on Docker containers fails using a custom MongoDB port:
```sh
$ docker logs --tail 400 rocketchat_rocketchat_1
...
MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.24.0.4:27017]
    at Pool.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Tried 1 times. Waiting 5 secs...
```

The deployment was perform as described in the [official tutorial](https://rocket.chat/docs/installation/docker-containers/) with the following configuration file (`docker-compose.yml`):
```yaml
version: '2'

services:
  rocketchat:
    image: rocket.chat:latest
    command: bash -c 'for i in `seq 1 30`; do node main.js && s=$$? && break || s=$$?; echo "Tried $$i times. Waiting 5 secs..."; sleep 5; done; (exit $$s)'
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://<host>:3000
      - MONGO_URL=mongodb://mongo:27027/rocketchat  # ?replicaSet=rs0
      - MONGO_OPLOG_URL=mongodb://mongo:27027/local  # ?replicaSet=rs0
      - Accounts_UseDNSDomainCheck=True
    depends_on:
      - mongo
    ports:
      - 3000:3000

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
     - ./data/dump:/dump
    command: mongod --port 27027 --replSet rs0  # --oplogSize 128 --storageEngine wiredTiger

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo
    command: 'bash -c "for i in `seq 1 30`; do mongo mongo/rocketchat --eval \"rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27027'' } ]})\" && s=$$? && break || s=$$?; echo \"Tried $$i times. Waiting 5 secs...\"; sleep 5; done; (exit $$s)"'
    depends_on:
      - mongo

  # hubot, the popular chatbot (add the bot user first and change the password before starting this image)
  hubot:
    image: rocketchat/hubot-rocketchat:latest
    restart: unless-stopped
    environment:
      - ROCKETCHAT_URL=http://<host>:3000
      - ROCKETCHAT_ROOM=GENERAL
      - ROCKETCHAT_USER=bot
      - ROCKETCHAT_PASSWORD=hB0tP5v@xi3at
      - BOT_NAME=bot
  # you can add more scripts as you'd like here, they need to be installable by npm
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    depends_on:
      - rocketchat
    volumes:
      - ./scripts:/home/hubot/scripts
  # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
    ports:
      - 3001:8088
```

> The deployment is perform successfully if the default MongoDB port is used (27017), which is not always desirable (when another MongoDB daemon already works on this port on the host).

### Steps to reproduce:

1. Deploy the Rocket Chat using Docker containers as specified in https://rocket.chat/docs/installation/docker-containers/ but using a non-default MongoDB port (see the config file above)
2. Try to run the Rocket Chat, it fails to start yielding the aforementioned error.

### Expected behavior:

Successful start of the Rocket Chat service after the deployment

### Actual behavior:

The Rocket Chat service fails to start with the exception listed above caused by the calls to improper (default) mongodb port given that another custom port is specified in the `docker-compose.yml`

### Server Setup Information:

- Version of Rocket.Chat Server: 
Version 1.3.2
Apps Engine Version 1.5.2

Commit
Hash 22894861c52cca1ff09f545db07c5259e9465791
Date  Wed Aug 14 00:23:11 2019 -0300
HEAD
1.3.2
Diego Sampaio
Merge pull request #15176 from RocketChat/release-1.3.2

- Operating System: 
Linux Ubuntu 16.04 x64 4.4.0-145-generic

- Deployment Method: docker

- Number of Running Instances: 
1

- DB Replicaset Oplog: 
Enabled

- NodeJS Version: 
v8.11.4

- MongoDB Version: 
4.2.0
Mongo Storage Engine:  wiredTiger

### Additional context

The Rocket chat attemps to connet to the invalid (dfault) mongodb port despite another custom port is specified in the config file.

### Relevant logs:

```
MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 172.24.0.4:27017]
    at Pool.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Tried 1 times. Waiting 5 secs...
```
