### ISSUE TITLE
Unable to Deploy Rocket.Chat in Windows 10 Pro via Docker

### ISSUE THREAD

**Issue by Prime-5** [RocketChat/Rocket.Chat#15272]
I followed the guide https://rocket.chat/docs/installation/community-supported-installation/windows-10-pro/ step by step until the last step where I got stuck.

The "docker-compose up" hanged on "waiting for connectin at port 27017", which I looked over StackOverflow and resolved by executing mongod and mongo.exe in other command windows. 2 connections were established but an "Unable to find Mongodb Oplog" error came, leading to the exit of docker_rocketchat_1

![Screenshot (474)](https://user-images.githubusercontent.com/35230163/63827619-76a50080-c981-11e9-8e5a-ff92f22ec50c.png)

I followed the first suggestion and appended --replSet rs0 in the yml file to db: command: field
Executing that gives "Mongo error: not master".

![Screenshot (475)](https://user-images.githubusercontent.com/35230163/63827733-df8c7880-c981-11e9-88cf-5ba17840c9c1.png)

I am new to all, Rocket.Chat, Docker and MongoDB. I have been trying different variants of the above for a day, but this is the furthermost I have reached. Could anyone help in resolving this issue?

**Comment by sahara18** [comment]
Hi! Faced similar problems, internet suggested to configure replica set. Try this docker-compose.yml.

```
version: '3.6'
services:
  mongo:
    image: mongo:3.2
    command: mongod --smallfiles --oplogSize 128 --replSet rs01

  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs01'', members: [ { _id: 0, host: ''mongo:27017'' } ]})"'
    depends_on:
      - mongo

  rocketchat:
    image: rocket.chat:latest
    restart: unless-stopped
    environment:
      - ROOT_URL=http://localhost
      - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs01
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs01
    depends_on:
      - mongo
    ports:
      - 80:3000
```

I presume it should be started like this for the first time
```
dc up -d mongo
dc up -d mongo-init-replica
dc up -d rocketchat
```

And ```dc up``` for the further use. Replica should be configured just once.
