### ISSUE TITLE
Rocket chat setup-wizard doesn't work after install

### ISSUE THREAD

**Issue by webdeveloper0429** [RocketChat/Rocket.Chat#15744]
```
rocketchat_1          | ➔ |  Rocket.Chat Version: 2.0.0                           |
rocketchat_1          | ➔ |       NodeJS Version: 8.11.4 - x64                    |
rocketchat_1          | ➔ |      MongoDB Version: 4.0.13                          |
rocketchat_1          | ➔ |       MongoDB Engine: mmapv1                          |
rocketchat_1          | ➔ |             Platform: linux                           |
rocketchat_1          | ➔ |         Process Port: 3000                            |
rocketchat_1          | ➔ |             Site URL: http://{mydomain}.com  |
rocketchat_1          | ➔ |     ReplicaSet OpLog: Enabled                         |
rocketchat_1          | ➔ |          Commit Hash: 92c00dc3c2                      |
rocketchat_1          | ➔ |        Commit Branch: HEAD   
```

I setup rocket chat and configured ssl as guide direct.
After visit my domain it redirected to setup-wizard.
But it shows black blank screen. so I checked console. it shows below.
```
cc945290c4dafe28d2516121de8ec1f7c477a095.js?meteor_js_resource=true:21 Mixed Content: The page at 'https://{mydomain}.com/setup-wizard' was loaded over HTTPS, but requested an insecure resource 'http://{mydomain}.com/__meteor__/dynamic-import/fetch'. This request has been blocked; the content must be served over HTTPS.
```

Anybody help...

**Comment by sampaiodiego** [comment]
btw, tranfered the issue to our main project repo.. as it is not totally related to our docker image

**Comment by starcraft0429** [comment]
@sampaiodiego I already tried out https in root url but it doesn't work
before, I installed rocket chat once and at that time I used http in root url and it worked well.

**Comment by sampaiodiego** [comment]
@starcraft0429 please try adding this environment variable to your start script as well: `OVERWRITE_SETTING_Site_Url=https://{mydomain}.com`

**Comment by starcraft0429** [comment]
```
rocketchat:
    image: rocket.chat
    command: bash -c 'for i in `seq 1 30`; do node main.js && s=$$? && break || s=$$?; echo "Tried $$i times. Waiting 5 secs..."; sleep 5; done; (exit $$s)'
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
```
To this command?
