### ISSUE TITLE
Custom oauth not created via docker-compose

### ISSUE THREAD

**Issue by mbassiouny33** [RocketChat/Rocket.Chat#15891]
### Steps to reproduce:

1. run the docker-compose file
2. go to rocketchat address

### Expected behavior:
custom oAuth should be created and activated.

### Actual behavior:
Nothing! the custom oauth is not created

### Server Setup Information:

- Version of Rocket.Chat Server: 2.0 since 2.2 has a bug with oauth
- Operating System: 
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: default one of the docker image
- MongoDB Version:4

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

Rocket.chat 2.2 has an issue with oAuth. So I decided to use 2.0.  see : https://github.com/RocketChat/Rocket.Chat/issues/15876

Now with 2.2 adding a custom oAuth via the web interface works fine. But if I try to create a custom oAuth via environment variables it does not work.

Here's my docker-compose.yml file, based on the official doc and this [link](https://gitlab.medelexis.ch/elexis/elexis-environment/blob/b18cc1ca760f585a1eb88cdd008edc674b34e03f/docker/compose/rocketchat.yml): 

```
version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:2.0.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3500
      - ROOT_URL=http://rk.domain.me:3500
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.email
      - ADMIN_USERNAME=admin
      - ADMIN_PASS=password
      - ADMIN_EMAIL=me@sdfsdf.com
      - OVERWRITE_SETTING_Show_Setup_Wizard=completed
      - Accounts_OAuth_Custom-Keycloak=true
      - Accounts_OAuth_Custom-Keycloak-url=https://keycloack.domain.me:9445/auth
      - Accounts_OAuth_Custom-Keycloak-token_path=/realms/master/protocol/openid-connect/token
      - Accounts_OAuth_Custom-Keycloak-token_sent_via=Header
      - Accounts_OAuth_Custom-Keycloak-identity_token_sent_via=header
      - Accounts_OAuth_Custom-Keycloak-identity_path=/realms/master/protocol/openid-connect/userinfo
      - Accounts_OAuth_Custom-Keycloak-authorize_path=/realms/master/protocol/openid-connect/auth
      - Accounts_OAuth_Custom-Keycloak-scope=openid
      - Accounts_OAuth_Custom-Keycloak-id=rocket_client
      - Accounts_OAuth_Custom-Keycloak-secret=5ff81b24-81fb-4f92-8a3d-c139ab4ecf64
      - Accounts_OAuth_Custom-Keycloak-login_style=redirect
      - Accounts_OAuth_Custom-Keycloak-button_label_text=Login via Keycloak
      - Accounts_OAuth_Custom-Keycloak-button_label_color="#FFFFFF"
      - Accounts_OAuth_Custom-Keycloak-button_color="#13679A"
      - Accounts_OAuth_Custom-Keycloak-username_field=preferred_username
      - Accounts_OAuth_Custom-Keycloak-merge_users=false
#       - OVERWRITE_SETTING_Show_Setup_Wizard=completed 
#       - HTTP_PROXY=http://proxy.domain.com
#       - HTTPS_PROXY=http://proxy.domain.com
    depends_on:
      - mongo
    ports:
      - 3500:3500
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: tora.domain.me"

  mongo:
    image: mongo:4.0
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
     #- ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    labels:
      - "traefik.enable=false"

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:4.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo

  # hubot, the popular chatbot (add the bot user first and change the password before starting this image)
  hubot:
    image: rocketchat/hubot-rocketchat:latest
    restart: unless-stopped
    environment:
      - ROCKETCHAT_URL=rocketchat:3500
      - ROCKETCHAT_ROOM=GENERAL
      - ROCKETCHAT_USER=bot
      - ROCKETCHAT_PASSWORD=botpassword
      - BOT_NAME=bot
  # you can add more scripts as you'd like here, they need to be installable by npm
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    depends_on:
      - rocketchat
    labels:
      - "traefik.enable=false"
    volumes:
      - ./scripts:/home/hubot/scripts
  # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
    ports:
      - 3001:8080

  #traefik:
  #  image: traefik:latest
  #  restart: unless-stopped
  #  command: >
  #    traefik
  #     --docker
  #     --acme=true
  #     --acme.domains='your.domain.tld'
  #     --acme.email='your@email.tld'
  #     --acme.entrypoint=https
  #     --acme.storagefile=acme.json
  #     --defaultentrypoints=http
  #     --defaultentrypoints=https
  #     --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
  #     --entryPoints='Name:https Address::443 TLS.Certificates:'
  #  ports:
  #    - 80:80
  #    - 443:443
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock

```
