### ISSUE TITLE
Docker compose deployment doesn't publish service on containers IP

### ISSUE THREAD

**Issue by whitecolor** [RocketChat/Rocket.Chat#15972]
Starting on docker for windows.

Following config:
```yaml
rocketchat:
    image: rocket.chat:latest
    command: bash -c 'for i in `seq 1 30`; do node main.js && s=$$? && break || s=$$?; echo "Tried $$i times. Waiting 5 secs..."; sleep 5; done; (exit $$s)'
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://chat.rocket.dk:3000
      - MONGO_URL=mongodb://${DOCKER_HOST_IP}/rocketchat
      - MONGO_OPLOG_URL=mongodb://${DOCKER_HOST_IP}:27017/local
      - Accounts_UseDNSDomainCheck=True
  ports:
      - 4000:3000
```
It runs ok:
![image](https://user-images.githubusercontent.com/736697/70793432-19607e00-1dbd-11ea-8c6f-12ee433c9929.png)

It is accessible on `localhost:4000`

But I want to access the service using containers IP which looks like `172.20.0.3`, but can not. Port is not published on this IP. Can this be fixed/tuned somehow?
