### ISSUE TITLE
environment variables wont populate administration configuration

### ISSUE THREAD

**Issue by raph2i** [RocketChat/Rocket.Chat#17065]
### Description:
Environment variables set via docker-compose.yml wont get recognized by rocket.chat

https://rocket.chat/docs/administrator-guides/settings-via-env-vars/#managing-settings-using-environment-variables
https://forums.rocket.chat/t/how-to-set-ldap-settings-using-environment-variables/1678/3

Uppercase and Camelcase wont change anything.

### Steps to reproduce:

1. Add environment variables to your docker-compose.yml
2. docker-compose up
3. check administration

### Expected behavior:

LDAP setting fields being populated from env variables

### Actual behavior:

LDAP settings are not populated with values from environment variables

### Server Setup Information:

- Version of Rocket.Chat Server: 3.0.7
- Operating System: linux
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.14.0
- MongoDB Version: 4.0.17

### Client Setup Information

- Desktop App or Browser Version: Firefox
- Operating System: Manjaro Linux

### Additional context
docker-compose.yml cutout:
    environment:
      PORT: 3000
      ROOT_URL: https://{{ rocketchat_domain }}
      MONGO_URL: mongodb://mongo:27017/rocketchat
      MONGO_OPLOG_URL: mongodb://mongo:27017/local
      ADMIN_USERNAME: REDACTED
      ADMIN_PASS: REDACTED
      ADMIN_EMAIL: REDACTED
      LDAP_Enable: 'true'
      LDAP_BASEDN: REDACTED
      LDAP_HOST: openldap
      LDAP_RECONNECT: 'true'
      LDAP_PORT: 389
      LDAP_AUTHENTICATION: 'true'
      LDAP_AUTHENTICATION_USERDN: REDACTED
      LDAP_AUTHENTICATION_PASSWORDREDACTED
      LDAP_USERNAME_FIELD: uid
      LDAP_DEFAULT_DOMAIN: {{ ldap_domain }}
      LDAP_UNIQUE_IDENTIFIER_FIELD: entryUUID
      LDAP_User_Search_Filter: (&(objectClass=inetOrgPerson)(uid=#{username}))
      LDAP_User_Search_Scope: sub
      LDAP_User_Search_Field: uid

### Relevant logs:

```
docker-compose exec rocketchat /bin/bash
rocketchat@7dfe8becc663:/app/bundle$ env
DEPLOY_METHOD=docker
LDAP_Enable=true
LDAP_PORT=389
LDAP_RECONNECT=true
HOSTNAME=7dfe8becc663
ROOT_URL=REDACTED
LDAP_AUTHENTICATION_USERDN=REDACTED
LDAP_AUTHENTICATION=true
NODE_ENV=production
LDAP_USERNAME_FIELD=uid
Accounts_AvatarStorePath=/app/uploads
LDAP_UNIQUE_IDENTIFIER_FIELD=entryUUID
LDAP_HOST=openldap
PWD=/app/bundle
HOME=/tmp
LDAP_BASEDN=REDACTED
MONGO_URL=mongodb://mongo:27017/rocketchat
PORT=3000
NODE_VERSION=12.14.0
affinity:container==2a7ba2a8e37d132a36a08e64d1bb0716bc78d21c47aab89575c0979c7ce97cc1
LDAP_User_Search_Scope=sub
TERM=xterm
LDAP_User_Search_Field=uid
MONGO_OPLOG_URL=mongodb://mongo:27017/local
ADMIN_PASS=REDACTED
LDAP_DEFAULT_DOMAIN=REDACTED
SHLVL=1
LDAP_AUTHENTICATION_PASSWORD=REDACTED
LDAP_User_Search_Filter=(&(objectClass=inetOrgPerson)(uid=#{username}))
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ADMIN_EMAIL=REDACTED
ADMIN_USERNAME=REDACTED
_=/usr/bin/env

```

**Comment by 564064202** [comment]
Sir,please give us your docker-compose.yml file,and we can try to analyze it

**Comment by raph2i** [comment]
Hi @564064202 , sure :)

docker-compose.yml is filled via ansible / jinja2

```
version: '3'

volumes:
  uploads:
    driver: local-persist
    driver_opts:
      mountpoint: ${CONTAINERVOLUME}/uploads/
  data:
    driver: local-persist
    driver_opts:
      mountpoint: ${CONTAINERVOLUME}/data/

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: always
    volumes:
      - uploads:/app/uploads
    environment:
      PORT: 3000
      ROOT_URL: https://{{ rocketchat_domain }}
      MONGO_URL: mongodb://mongo:27017/rocketchat
      MONGO_OPLOG_URL: mongodb://mongo:27017/local
      ADMIN_USERNAME: {{ rocketchat_admin_username }}
      ADMIN_PASS: {{ rocketchat_admin_password }}
      ADMIN_EMAIL: {{ server_admin_email }}
      LDAP_Enable: 1
      LDAP_BaseDN: dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}
      LDAP_Host: openldap
      LDAP_Reconnect: 1
      LDAP_Port: 389
      LDAP_Authentication: 1
      LDAP_Authentication_UserDN: cn={{ ldap_readonly_username }},dc={{ ldap_domain.split('.')[0] }},dc={{ ldap_domain.split('.')[1] }}
      LDAP_Authentication_Password: {{ ldap_readonly_password }}
      LDAP_Username_Field: uid
      LDAP_Default_Domain: {{ ldap_domain }}
      LDAP_Unique_Identifier_Field: entryUUID
      LDAP_User_Search_Filter: (&(objectClass=inetOrgPerson)(uid=#{username}))
      LDAP_User_Search_Scope: sub
      LDAP_User_Search_Field: uid
    depends_on:
      - mongo
    networks:
      - ldap
      - reverse-proxy
      - rocketchat
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rocketchat.rule=Host(`{{ rocketchat_domain }}`)"
      - "traefik.http.routers.rocketchat.tls.certresolver=le"
      - "traefik.http.routers.rocketchat.entrypoints=websecure"
      - "traefik.docker.network=reverse-proxy"

  mongo:
    image: mongo:4.0
    restart: always
    volumes:
     - data:/data/db
     #- ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    networks:
      - rocketchat

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:4.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo
    networks:
      - rocketchat

networks:
  rocketchat:
  ldap:
    external: true
  reverse-proxy:
    external: true
```
