### ISSUE TITLE
SMTP configuration problem on AWS

### ISSUE THREAD

**Issue by radommaciej** [RocketChat/Rocket.Chat#17308]
### Description:

I am trying to configure SMTP emails in rocket chat, deployed on Ec2 instance using docker and nginx, i try to do it for diffrent email providers and everytime i see same errors. Chat works very good but i cannot send emails

### Steps to reproduce:
Here is my configurtion on rocket chat:
Protocol: SMTP
HOST: email-smtp.eu-central-1.amazonaws.com
Ignore TLS: false
SMTP poll: true
Username: correct
Password: correct
Email`s sender: my_address

On AWS machine all ports are enabled and it still doesnt work

Here is my nginx file, mydomain is example value, i am using here my domain name where chat is recheable:
 ```server {
 listen 443 ssl;
 server_name www.chat.mydomain.eu;
 ssl_certificate /etc/letsencrypt/live/www.mydomain.eu/fullchain.pem;
 ssl_certificate_key /etc/letsencrypt/live/www.mydomain.eu/privkey.pem;
 ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
 ssl_prefer_server_ciphers on;
 ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
 root /usr/share/nginx/html;
 index index.html index.htm;
 # Make site accessible from http://localhost/
 server_name localhost;
 location / {
     proxy_pass http://localhost:3000/;
     proxy_http_version 1.1;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection "upgrade";
     proxy_set_header Host $http_host;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
     proxy_set_header X-Forward-Proto http;
     proxy_set_header X-Nginx-Proxy true;
     proxy_redirect off;
 }
 }
 server {
 listen 80;
 server_name www.mydomain.eu;
 return 301 https://$host$request_uri;
 }
```

Here is my docker file:
```
version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=https://www.chat.mydomain.eu
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.email
#       - HTTP_PROXY=http://proxy.domain.com
#       - HTTPS_PROXY=http://proxy.domain.com
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 587:587
      - 465:465
      - 25:25
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"

  mongo:
    image: mongo:4.0
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
     #- ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"

 this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:4.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo

  # hubot, the popular chatbot (add the bot user first and change the password before starting this image)
  hubot:
    image: rocketchat/hubot-rocketchat:latest
    restart: unless-stopped
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ROOM=GENERAL
      - ROCKETCHAT_USER=bot
      - ROCKETCHAT_PASSWORD=botpassword
      - BOT_NAME=bot
  # you can add more scripts as you'd like here, they need to be installable by npm
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    depends_on:
      - rocketchat
    labels:
      - "traefik.enable=false"
    volumes:
      - ./scripts:/home/hubot/scripts
  # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
    ports:
      - 3001:8080
```

### Expected behavior:

After click send test email, email should be send

### Actual behavior:
I see error like this:
```Exception in defer callback: Error: Greeting never received     at SMTPConnection._formatError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)     at SMTPConnection._onError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:531:20)     at Timeout.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:472:22)     at listOnTimeout (internal/timers.js:549:17)     at processTimers (internal/timers.js:492:7) {   code: 'ETIMEDOUT',   command: 'CONN' } ```

Or if i switch SMTP port to 587:
```
Exception in defer callback: Error: Invalid login: 535 Authentication Credentials Invalid     at SMTPConnection._formatError (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:558:19)     at SMTPConnection._actionAUTHComplete (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:1254:34)     at SMTPConnection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:341:26)     at SMTPConnection._processResponse (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:707:20)     at SMTPConnection._onData (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:510:14)     at TLSSocket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/email/node_modules/node4mailer/lib/smtp-connection/index.js:658:51)     at TLSSocket.emit (events.js:311:20)     at TLSSocket.EventEmitter.emit (domain.js:482:12)     at addChunk (_stream_readable.js:294:12)     at readableAddChunk (_stream_readable.js:275:11)     at TLSSocket.Readable.push (_stream_readable.js:209:10)     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {   code: 'EAUTH',   response: '535 Authentication Credentials Invalid',   responseCode: 535,   command: 'AUTH PLAIN' } 
```

### Server Setup Information:

- Version of Rocket.Chat Server: 3.2.0
- Operating System: Ubuntu 18
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: 12
- MongoDB Version: 4

### Additional context

Maybe i should add something to my docker-compose.yml file or nginx server
