### ISSUE TITLE
High memory consumption node v3.0.2

### ISSUE THREAD

**Issue by dsalgueiror** [RocketChat/Rocket.Chat#17537]
Hello,

We have reviewed the memory metrics of our rocketchat server and we have observed that the nodejs process is consuming a lot of physical memory starting to use SWAP memory.

```
KiB Mem: 8009104 total, 362216 free, 7428484 used, 218404 buff / cache
KiB Swap: 2097148 total, 980988 free, 1116160 used. 318680 avail Mem

  PID USER PR NI VIRT RES SHR S% CPU% MEM TIME + COMMAND
 5553 rocketc + 20 0 10.9g 6.7g 10820 S 50.0 87.6 17928: 13 node

```

The environment data is:

> 1931/5000
> Rocket.Chat
> Version 3.0.2
> Apps Engine Version 1.12.0
> Database migration 174
> Database migration date March 13, 2020 2:54 PM
> Installation October 10, 2019 8:57 AM
> uptime 53 days, 2 hours, 41 minutes, 43 seconds
> Deployment ID XWvCqXfREAvh7YM2X
> PID 5553
> Running Instances 1
> OpLog Enabled
> Commit
> Hash 05af21bbe97542945b92fc2aa4bb4e89a497e700
> Date Fri Feb 21 16:00:06 2020 -0300
> HEAD branch
> Label 3.0.2
> Author Diego Sampaio
> Subject Merge pull request # 16674 from RocketChat / release-3.0.2
> Runtime environment
> Linux OS type
> Linux OS platform
> OS x64 architecture
> OS version 3.10.0-1062.12.1.el7.x86_64
> Versiond of Node v12.14.0
> Mongo Version 4.2.3
> Mongo Storage Engine wiredTiger
> OS uptime 62 days, 3 hours, 57 minutes, 30 seconds
> SO Load Average 0.82, 0.84, 0.77
> Total OS Memory 7.64 GB
> Free OS Memory 236.20 MB
> CPU count 4
> Construction environment
> Linux OS platform
> OS x64 architecture
> OS version 5.0.0-1031-azure
> Versiond of Node v12.14.0
> Date February 21, 2020 20:09
> Usage
> Total Users 406
> Active Users 406
> Rocket.Chat App Users 0
> Inactive Users 0
> Total Connected Users 160
> Connected Users 37
> Absent Users 123
> Offline Users 246
> Total Rooms 2220
> Total Channels 1
> Total Private Groups 119
> Total direct message rooms 2,100
> Total chat rooms 0
> Total Discussions 64
> Total threads 4033
> Total Posts 237822
> Total messages on channels 420
> Total messages in private groups 75982
> Total messages in direct messages 162 540
> Total Messages in Livechats 0
> Total Uploads 1987
> Total Uploads Size 1.50 GB
> Total Installed Apps 0
> Total Active Apps 0
> Total Integrations 0
> Total Incoming Integrations 0
> Total Active Incoming Integrations 0
> Total Outgoing Integrations 0
> Total Active Outgoing Integrations 0
> Total Integrations With Script Enabled 0

Reviewing node memory metrics we only get the following:

```
process.memoryUsage (5553);
{
  rss: 17453056,
  heapTotal: 5656576,
  heapUsed: 3127360,
  external: 1350724
}
```

Any ideas?

Thank you

**Comment by BobWs** [comment]
Having the same problem. Is there a way to Limt memory usage of container? I'm on docker Synology.

**Comment by dsalgueiror** [comment]
In my case I have 2 environments, one with Docker for test and the other installed as an operating system service via yum, in Docker I have no problems but in which it is installed in service mode https://rocket.chat/docs/installation/manual-installation/centos/ this is the one that consumes a lot of memory from one day to the next, the process is nodejs.

Finally I have had to restart the service but analyze the reason or cause of the problem.

As for limiting container memory, if you use docker-compose you can limit it as follows:

Example:

```
services:
    appnode:
      image: appimage
      environment:
        MONGO_HOST: "db"
      resources:
        limits:
          cpus: '1.5'
          memory: 500M
        reservations:
          cpus: '1.0'
          memory: 200M
      ports:
        - "8000:8000"
        - "25565:25565"
      networks:
        - netest
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
```

Thank you.
