### ISSUE TITLE
Consider adding the ability to add branding to Rocket Chat 

### ISSUE THREAD

**Issue by robbyoconnor** [RocketChat/Rocket.Chat#17555]
If people want to add logos, it often doesn't look fantastic. Moreover, right now figuring out the different variables to tweak is really, really hard for a newcomer(I'm not a newcomer) and it's a moving target. 

**DO NOT** throw this in the enterprise product please, but enterprise customers will want this to look good. 

It looks fantastic on the community server: 

![image](https://user-images.githubusercontent.com/23088/81258266-4a0eb180-9003-11ea-8707-9704c68a8431.png)

But requires hacks to look good otherwise: 

looks crumby. 
![image](https://user-images.githubusercontent.com/23088/81259380-d5894200-9005-11ea-9093-b47a91dfa01c.png)

Via CSS I can edit margins on the left and right and get it to look like this: 

![image](https://user-images.githubusercontent.com/23088/81259679-74ae3980-9006-11ea-8784-84082dff89a0.png)

```css
.side-nav .footer img {
content:url("/assets/logo.png");
  object-fit: cover;
}

.sidebar__footer:not(:empty) {
    margin-left: auto;
    margin-right: auto;
}
```

Allowing us to have knobs to tweak things so it looks better than it does now would be great. It seems like it was designed with the Rocket Chat logo in mind, but that's not how many use it in all likelihood.
