### ISSUE TITLE
Problem with docker-compose startup

### ISSUE THREAD

**Issue by brightbulbnz** [RocketChat/Rocket.Chat#1880]
I have been successfully running Rocket Chat using the official image (`rocket.chat`).

When I switch to the latest build (`rocketchat/rocket.chat:latest`), the container throws the following:
```

/app/bundle/programs/server/node_modules/fibers/future.js:278
                                                throw(ex);
                                                      ^
Error: failed to connect to [mongo:27017]
    at Object.Future.wait (/app/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /app/bundle/programs/server/packages/accounts-base.js:1814:4
    - - - - -
    at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
    at process._tickCallback (node.js:448:13)
```

I use docker-compose and only swap out the 'image' attribute, leaving everything else the same. Are these images supposed to behave differently?

**Comment by Sing-Li** [comment]
@brightbulbnz - start mongo first,   make sure it is up and running.  THEN start rocketchat.

Please see detailed documentation here:

https://github.com/RocketChat/Rocket.Chat/wiki/Deploy-with-Docker

Please close issue if this works for you.  Thanks.

**Comment by brightbulbnz** [comment]
Thanks, I will try that now. 

I suppose this issue would resolve this problem:
https://github.com/docker/compose/issues/374

Is [this](http://stackoverflow.com/a/21194386) something that can be added to the dockerfile perhaps?

**Comment by brightbulbnz** [comment]
Sorry, that didn't resolve the issue.
Even giving mongo a long time to launch before launching Rocket Chat caused the same exception.

**Comment by Sing-Li** [comment]
Pls post your docker compose file.

**Comment by Sing-Li** [comment]
Please reopen if you still have problem.  Or look us up on https://demo.rocket.chat/  weekdays UTC-2

**Comment by brightbulbnz** [comment]
Sorry for the delay.

I'm still having this issue, however I'd like to reiterate that this works fine if I use the official container (`rocket.chat`). It's only when I try to switch to `rocketchat/rocket.chat:latest` that I have a problem.

Here's my docker-compose.yml:
```
mongo:
  image: mongo
  restart: always
  volumes:
   - /srv/rocketchat/db:/data/db
   - /srv/rocketchat/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:latest
  restart: always
  environment:
    - ROOT_URL=http://chat-test/
    - VIRTUAL_HOST=chat-test
    - VIRTUAL_PORT=3000
    - mongo:db
  ports:
    - 3000:3000
  external_links:
    - mongotest:db
```
