### ISSUE TITLE
MAIL_URL needed when deploying with docker

### ISSUE THREAD

**Issue by pescobar** [RocketChat/Rocket.Chat#1901]
I deployed rocketchat with docker and after configuring smtp in the web interface I was getting this message:

```
Mail not sent; to enable sending, set the MAIL_URL environment variable.
```

I had to modify file ```docker-compose.yml``` file to add the required env var pointing to my smtp and then restart the container. Something like this:

```
rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://mydomain.com
    - MAIL_URL=smtp://smtp.mydomain.com:25
  links:
    - db:db
  ports:
    - 3000:3000
```
