### ISSUE TITLE
Last lines of Custom CSS are deleted

### ISSUE THREAD

**Issue by TBG-FR** [RocketChat/Rocket.Chat#19405]
### Description:

The custom CSS you can provide in Administration Panel (`/admin/Layout`) is cut at the end, and so some CSS rules are broken.

### Steps to reproduce:

1. Go to Administration > Layout > Custom CSS
2. Provide the following CSS content
3. Save
4. Refresh, open console (F12) and go to Style Editor to check the `theme.css` content

```css
.first-rule {
    background-color: white;
}

.second-rule {
    background-color: red;
}

/* this item will be cut */
.dummy-entry {
    color: whitesmoke;
}
```

### Expected behavior:

The `theme.css` file should contain the following input:
```css
.first-rule {
    background-color: white;
}

.second-rule {
    background-color: red;
}

/* this item will be cut */
.dummy-entry {
    color: whitesmoke;
}
```

### Actual behavior:

The `theme.css` file contains the following input:
```css
.first-rule {
    background-color: white;
}

.second-rule {
    background-color: red;
}

/* this item will be cut */
.dummy-entry {
 color:whitesmok
```

**^^^^ As you can see, the end of the file is missing**

### Server Setup Information:

- Version of Rocket.Chat Server: 3.7.1
- Operating System: Debian
- Number of Running Instances: 3
- DB Replicaset Oplog: Enabled
- NodeJS Version: v12.16.1
- MongoDB Version: 3.6.20

### Client Setup Information

- Desktop App or Browser Version: Firefox 80.0.1
- Operating System: Windows 10

### Additional context

N/A

### Relevant logs:

N/A
