### ISSUE TITLE
Initial Setup Wizard

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#2233]
Some config options are too important to be left for later. We should have a way to mark some settings as part of of the *Setup Wizard* so the admin will have to complete the before using the system for the first time.

**Comment by marceloschmidt** [comment]
Relates to #2232

**Comment by engelgabriel** [comment]
Add https://github.com/RocketChat/Rocket.Chat/issues/6225

**Comment by marceloschmidt** [comment]
@ggazzo @karlprieb could one of you work on this sometime mid-term? it would be very useful :)

**Comment by huiminzeng** [comment]
hello! I have got a problem with this. 
I am using docker-compose to deploy rocketchat, and have already created an Admin with environment variables. But still, when i open the browser and open the localhost:3000 tab, it jumps to the setup-wizard automatically. Could you please tell me, whether this is an issue or it is just me made some mistakes?
thank you!

**Comment by ggazzo** [comment]
@karlprieb

**Comment by karlprieb** [comment]
@huiminzeng If is the first time you run a server you will enter on the setup wizard even if you already have an admin user.

When you open localhost:3000 the first time do you see the first step of the setup wizard (the step with a form to create a user) or do you see the second step (Organization Info)?

**Comment by huiminzeng** [comment]
hi @karlprieb ! Thanks for your instruction. What i saw was always the first step, which means i have to create an Admin. Moreover, i couldn't use the Admin, which i defined with environment variables. Thus, I had to give a new account.
I opened an issue yesterday as well. There are some screenshot. I will appreciate it, if you could please have a look.  https://github.com/RocketChat/Rocket.Chat/issues/10860
Thanks!

**Comment by sawo** [comment]
Is there a way to avoid the setup wizard by setting all variables from env vars? I've set up the admin user, so when I open the chat in a browser, it jumps to the 2nd page of the setup wizard.

**Comment by abate** [comment]
I'm struggling with this problem as well . Do we have a solution ?

**Comment by sawo** [comment]
Finally, I managed to avoid the wizard by adding this environment variable: `OVERWRITE_SETTING_Show_Setup_Wizard=completed` I hope this helps.

**Comment by abate** [comment]
I did that, but I guess the setup wizard drop the database before even asking questions, and did not forgive my initial attempts (even if I did abort the wizard) : So I lost all my data, users and configuration parameters. Not very happy about that :(

**Comment by fralau** [comment]
Upon reboot of the server, the wizard accidentally restarted and it seems that the configuration has been broken. Is there ANY way to save the configuration, or anything from it (messages, etc.)?

**Comment by ChrisJBurns** [comment]
Is there a way to completely automate the setup-wizard? The manual task is a bit annoying. We install via Helm so would be great if we could get all of the setup-wizard stuff sorted before we even go to the applicaiton.

**Comment by ChrisJBurns** [comment]
The best I've got is specifying the below in my Flux release for RocketChat

```yaml
    extraEnv: |
      - name: USE_NATIVE_OPLOG
        value: "true"
      - name: OVERWRITE_SETTING_Show_Setup_Wizard
        value: "completed"
      - name: ADMIN_USERNAME
        value: "EXAMPLE"
      - name: ADMIN_PASS
        value: "EXAMPLE"
      - name: ADMIN_EMAIL
        value: "EXAMPLE"
      - name: Accounts_OAuth_Custom_Keycloak
        value: "true"
      - name: Accounts_OAuth_Custom_Keycloak_url
        value: "EXAMPLE"
```
