### ISSUE TITLE
Migration Issues after Update Release Version

### ISSUE THREAD

**Issue by mrhavel** [RocketChat/Rocket.Chat#23729]
### Description:
* Just updated my six weeks old Rocket Chat Docker Stack to the current "lastest" Version and got database migration issues.
   * image: registry.rocket.chat/rocketchat/rocket.chat:latest

* My docker-compose Template is the following: 
    * https://github.com/RocketChat/Rocket.Chat/blob/develop/docker-compose.yml

```yml
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    depends_on:
      - mongo
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"

```

### Actual behavior:

Rocket Chat seems to be stuck in its Database Migration process. Maybe just a database Script is missing.

Got this logs:

```
{"level":40,"time":"2021-11-17T06:51:34.602Z","pid":57,"hostname":"6543064ea404","name":"Migrations","msg":"Not migrating, control is locked. Attempt 28/30. Trying again in 10 seconds."}
/app/bundle/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

Error: Can't find migration version 243
    at migrateDatabase (server/lib/migrations.ts:229:9)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
    at migrateDatabase (server/lib/migrations.ts:181:11)
Tried 4 times. Waiting 5 secs...
LocalStore: store created at
LocalStore: store created at
LocalStore: store created at
{"level":40,"time":"2021-11-17T06:52:00.966Z","pid":73,"hostname":"6543064ea404","name":"Migrations","msg":"Not migrating, control is locked. Attempt 0/30. Trying again in 10 seconds."}
```

### Server Setup Information:

The first Rocket Chat installation is 6 weeks ago.

- Version of Rocket.Chat Server: latest
- Operating System: Debian
- Deployment Method: docker
- Number of Running Instances: 1 
- DB Replicaset Oplog: ??
- NodeJS Version: container
- MongoDB Version: container
