### ISSUE TITLE
setup-wizard page  is not work

### ISSUE THREAD

**Issue by swcloudy** [RocketChat/Rocket.Chat#24025]
os:centos 7.6

Dec 25 06:33:29 localhost rocketchat: +-----------------------------------------------+
Dec 25 06:33:29 localhost rocketchat: |                 SERVER RUNNING                |
Dec 25 06:33:29 localhost rocketchat: +-----------------------------------------------+
Dec 25 06:33:29 localhost rocketchat: |                                               |
Dec 25 06:33:29 localhost rocketchat: |  Rocket.Chat Version: 4.2.2                   |
Dec 25 06:33:29 localhost rocketchat: |       NodeJS Version: 12.22.1 - x64           |
Dec 25 06:33:29 localhost rocketchat: |      MongoDB Version: 5.0.5                   |
Dec 25 06:33:29 localhost rocketchat: |       MongoDB Engine: wiredTiger              |
Dec 25 06:33:29 localhost rocketchat: |             Platform: linux                   |
Dec 25 06:33:29 localhost rocketchat: |         Process Port: 3000                    |
Dec 25 06:33:29 localhost rocketchat: |             Site URL: http://localhost:3000/  |
Dec 25 06:33:29 localhost rocketchat: |     ReplicaSet OpLog: Enabled                 |
Dec 25 06:33:29 localhost rocketchat: |          Commit Hash: ab3baf2f31              |
Dec 25 06:33:29 localhost rocketchat: |        Commit Branch: HEAD                    |
Dec 25 06:33:29 localhost rocketchat: |                                               |
Dec 25 06:33:29 localhost rocketchat: +-----------------------------------------------+

![image](https://user-images.githubusercontent.com/27907573/147387849-0eca26d7-240e-43bb-a503-d128c52c2230.png)

firewalld  and selinux is diable

anyone can help？

**Comment by foyue5666** [comment]
I met the same problem just now
now i'm trying to reinstall it, maybe this can work....
I’d be grateful if you could help me.

**Comment by dudanogueira** [comment]
Hi! Please, inform how you deployed your system.

Also, if possible, try replicating this on a docker deployment.

Thanks!

**Comment by let5sne** [comment]
i hava the same problem
here is my docker-compose.yml it's running on a centos  VMware,it's ip: 192.168.137.100
```
version: '2'

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://chat.example.com
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
#       - MAIL_URL=smtp://smtp.email
#       - HTTP_PROXY=http://proxy.domain.com
#       - HTTPS_PROXY=http://proxy.domain.com
    depends_on:
      - mongo
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"

  mongo:
    image: mongo:4.0
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
     #- ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
    labels:
      - "traefik.enable=false"

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:4.0
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo

  # hubot, the popular chatbot (add the bot user first and change the password before starting this image)
  hubot:
    image: rocketchat/hubot-rocketchat:latest
    restart: unless-stopped
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ROOM=GENERAL
      - ROCKETCHAT_USER=bot
      - ROCKETCHAT_PASSWORD=botpassword
      - BOT_NAME=bot
  # you can add more scripts as you'd like here, they need to be installable by npm
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    depends_on:
      - rocketchat
    labels:
      - "traefik.enable=false"
    volumes:
      - ./scripts:/home/hubot/scripts
  # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
    ports:
      - 3001:8080

  #traefik:
  #  image: traefik:latest
  #  restart: unless-stopped
  #  command: >
  #    traefik
  #     --docker
  #     --acme=true
  #     --acme.domains='your.domain.tld'
  #     --acme.email='your@email.tld'
  #     --acme.entrypoint=https
  #     --acme.storagefile=acme.json
  #     --defaultentrypoints=http
  #     --defaultentrypoints=https
  #     --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
  #     --entryPoints='Name:https Address::443 TLS.Certificates:'
  #  ports:
  #    - 80:80
  #    - 443:443
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
```
it's my host nginx config
```
server {
    listen       80;
    server_name  chat.example.com;

    # security
    include                 ../conf/security.conf;
	
    # letsencrypt-acme-challenge
    include ../conf/letsencrypt-acme-challenge.conf;
	
    # additional config
    include ../conf/general.conf;
	
	location / {
	proxy_pass http://192.168.137.100:3000;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_connect_timeout 60;
        proxy_read_timeout 600;
        proxy_send_timeout 600;
    }
}
```
but when I visit on browser

```
![image](https://user-images.githubusercontent.com/3231367/147483248-e63a6592-c08f-4b9e-8c28-74900c742a8a.png)

![image](https://user-images.githubusercontent.com/3231367/147483052-5ee9761e-1ba4-4e87-af20-dab231a65506.png)

```
