### ISSUE TITLE
:username: should display the avatar of a username

### ISSUE THREAD

**Issue by bott0r** [RocketChat/Rocket.Chat#2495]
It would be great to utilize the "alias icon", currently filled with :ghost:, to post to channels with dynamic avatars. This becomes handy when sending messages utilizing web-hooks. 
Not sure if that is possible.

**Comment by rodrigok** [comment]
I didn't understand your question.

Are you trying to set avatars of another users in the integration user? You can do that:

```javascript
class Script {
 process_incoming_request({ request }) {
  return {
   content: {
     text: request.content.text,
     icon_url: '/avatar/rodrigo.rocket.team.jpg'
   }
  };
 }
}
```

**Comment by bott0r** [comment]
Hey,

I understand that i can change the icon_url to whatever i please, however this is a very static process, as,  every time this integration is used the icon_url avatar will be the one i specify.  What i like to do is use one Integration with multiple avatars with a icon_emoji: ":username:" so that when i feed the integration a username it displays the avatar for that given username.

e.g.
username : bott0r ->  icon_emoji: ":username:"

**Comment by bott0r** [comment]
What id like to do ist something along the lines of 

```css
    return {
      content:{
        username:request.content.message.from.first_name,
        icon_emoji: ':'+ 'ghost' +':' ,
        text: request.content.message.text
        // "attachments": [{
        //   "color": "#FF0000",
        //   "author_name": "Rocket.Cat",
        //   "author_link": "https://demo.rocket.chat/direct/rocket.cat",
        //   "author_icon": "https://demo.rocket.chat/avatar/rocket.cat.jpg",
        //   "title": "Rocket.Chat",
        //   "title_link": "https://rocket.chat",
        //   "text": "Rocket.Chat, the best open source chat",
        //   "fields": [{
        //     "title": "Priority",
        //     "value": "High",
        //     "short": false
        //   }],
        //   "image_url": "https://rocket.chat/images/mockup.png",
        //   "thumb_url": "https://rocket.chat/images/mockup.png"
        // }]
       }
    };
```
here ghost will be replaced with a variable feed by the weebhook, (in my case first_name) that should than link to my avatar
