### ISSUE TITLE
disappering images

### ISSUE THREAD

**Issue by Julime** [RocketChat/Rocket.Chat#2544]
Rocket.Chat version: 0.22.0
Since the last update images randomly disapper and appear when looking at them.
A reload sometimes fixes this for a few seconds. You can still view them in the files menu (right sidebar).
This issue does only take affect on uploaded images, not link previews.
![capturfiles_1](https://cloud.githubusercontent.com/assets/7944656/13873133/a1a14414-ecef-11e5-981e-1764ab5f0915.png)

**Comment by Julime** [comment]
![capturfiles_2](https://cloud.githubusercontent.com/assets/7944656/13873161/e82d8ece-ecef-11e5-963e-2128b39da75b.png)

**Comment by engelgabriel** [comment]
Are you using GridFS?

**Comment by Julime** [comment]
im using the docker mongodb image:
```
mongo:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128
  restart: always
```
