### ISSUE TITLE
Limit Number of Failed Login Attempts

### ISSUE THREAD

**Issue by richardwlu** [RocketChat/Rocket.Chat#2737]
Your Rocket.Chat version: 0.24

Is there a way to limit the number of failed login attempts for a user account? How much security can be put into place from this end?

This should be helpful for those of us who run an instance that is available on the public internet.

**Comment by engelgabriel** [comment]
I believe there is already. 5 per second, but we can change it.

**Comment by richardwlu** [comment]
That sounds good. Is there a way to also block based on IP?

**Comment by richardwlu** [comment]
I forgot to mention, does it still apply for LDAP users?

**Comment by engelgabriel** [comment]
Applies to all method calls, so it still apply for LDAP users.

**Comment by richardwlu** [comment]
And if there is a way to set how many attempts for how long til we lock it and possibly get a notification, that would be ideal.

**Comment by pa-de-solminihac** [comment]
👍 

I intended to secure it with fail2ban but I did not find where these failed login attempts are logged. I am using https://github.com/RocketChat/Deploy.to.Cloud/tree/master/GenericLinux to deploy, with this `docker-compose.yml`:
```yml
db:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles
web:
  image: rocketchat/rocket.chat
  environment:
    - MONGO_URL=mongodb://db:27017/meteor
    - ROOT_URL=https://rocket.domain.com
    - MAIL_URL=smtp://user@domain.com:password@smtp.example.com:465
  links:
    - db:db
  volumes:
    - logs:/home/app/logs
  expose:
    - "3000"
  ports:
    - "3000:3000"
```

Anyway, _5 per second_ is a much too high limit for my needs (and it does not seem to work, maybe I missed something?).
