### ISSUE TITLE
upgrade has failed from 5.3.5 to 5.4.0/1

### ISSUE THREAD

**Issue by ValheruPL** [RocketChat/Rocket.Chat#27727]
### Description:

Wizard steps instead login page after upgrade from 5.3.5 to 5.4.0/1

Server has upgraded successfully several times on 5.3.* family.

### Steps to reproduce:

docker pull registry.rocket.chat/rocketchat/rocket.chat:5.4.0
docker-compose stop rocketchat
docker-compose rm rocketchat
docker-compose up -d rocketchat

### Expected behavior:

I should see Login Page :))

### Actual behavior:

![image](https://user-images.githubusercontent.com/13285613/211813386-ba4bbdd9-7683-4e74-8935-16ea81279ff9.png)

### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.0/1
- Operating System: Ubuntu 20.04.4 LTS
- Deployment Method: docker
- Number of Running Instances: 1
- MongoDB Version: 4.4.15

Docker Compose:
```
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:5.4.0
    restart: on-failure
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: rocket.domain.tld"
    networks:
     iservices:
       aliases:
        - rocket.domain.tld
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - REG_TOKEN=${REG_TOKEN}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    ports:
      - 3000:3000

  mongodb:
    image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-4.4}
    restart: on-failure
    container_name: mongo
    volumes:
     - ./data/db:/data/db
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}
```

### Client Setup Information

- Desktop App or Browser Version: Chrome 108.0.5359.94, Firefox 108.0.1, Rocket Desktop 3.8.13
- Operating System: Ubuntu 22.10, Windows 11 Pro 

### Additional context

![image](https://user-images.githubusercontent.com/13285613/211815112-5b3010a2-b26e-47f0-8d8b-a538ea682967.png)
