### ISSUE TITLE
Files with `html` tags stored in a `FileSystem`  Storage Type are changed after download.

### ISSUE THREAD

**Issue by grape9292** [RocketChat/Rocket.Chat#28184]
### Description:

Files with `html` tags stored in a `FileSystem`  Storage Type are changed after download.

### Steps to reproduce:
1. Go to direct messages.
2. Send file `index.html` with content:
```
<!DOCTYPE html>
<html>

<body>

</body>
</html>
```
3. Download `index.html` file
4. Check the content of the file. It is different from that what has been sent
```
<!DOCTYPE html>
<html>

<body>

<noscript style=
```

### Expected behavior:
The downloaded file should not change
```
<!DOCTYPE html>
<html>

<body>

</body>
</html>
```

### Actual behavior:
The content of the downloaded file has been changed.
```
<!DOCTYPE html>
<html>

<body>

<noscript style=
```
### Server Setup Information:

- Version of Rocket.Chat Server: 5.4.2
- Operating System: Ubuntu 20.04.3 LTS
- Deployment Method: docker
- Number of Running Instances: 1
- DB Replicaset Oplog:
- NodeJS Version: v14.19.3
- MongoDB Version: 5.0.14 / wiredTiger (oplog enabled)
- Storage Type: FileSystem

### Client Setup Information

- Desktop App or Browser Version: 3.8.13
- Operating System: Ubuntu 20.04.3 LTS

### Additional context
Uploaded files are stored in the server's File system without change. They mutate after downloading

**Comment by grape9292** [comment]
Update
I figured out that while downloading you get `Rocket.chat` front-end code inside the downloaded file. 
For instance, I added some JS code inside the `body` tag and get more suspicious HTML code. I investigated the HTML tags and realized that it is a part of the rocket frontend page.

**Comment by IllTamer** [comment]
I can not reproduce this problem in Rocket.Chat server version 6.0.0. You can try to upgrade and try again.

**Comment by grape9292** [comment]
> I can not reproduce this problem in Rocket.Chat server version 6.0.0. You can try to upgrade and try again.

Upgraded to `6.0.0`. Nothing changed. Error still exists. 
Crucial point is that this error occurs only when `Storage Type` is `FileSystem`. With `GridFS` everything works correctly. But I don't want to store files in a mongo database because of the extra load on it. I need my files to be stored in a file system. 

![fileUploads](https://user-images.githubusercontent.com/120737593/224346844-9aa4f66e-d0f0-437a-97e1-1bbdeaef67ae.png)

Here is the docker-compose file that I use for testing:

```
version: '3'
services:

 nginx:
    image: nginx
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - nginx:/etc/nginx
    restart: always
    networks:
      rocketchat: ~


  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.0.0
    restart: on-failure
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: Host(`${DOMAIN}`)
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
#    volumes:
#      - ./uploads:/app/uploads
    environment:
      MONGO_URL: mongodb://mongodb:27017/rocketchat
      MONGO_OPLOG_URL: mongodb://mongodb:27017/local
      ROOT_URL: http://localhost
      PORT: 3000
      OVERWRITE_SETTING_Show_Setup_Wizard: completed
      ADMIN_USERNAME: test
      ADMIN_PASS: examplepass
      ADMIN_EMAIL: admin@example.com
      DEPLOY_METHOD: docker
#      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
    depends_on:
      - mongodb
    networks:
      rocketchat: ~

  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    restart: on-failure
    volumes:
      - ./data:/bitnami/mongodb
      - ./dump:/dump
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      rocketchat: ~

networks:
  rocketchat:
    driver: 'bridge'
```
