### ISSUE TITLE
Email domain check for admin user causes problem with automated installs

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/Rocket.Chat#2895]
Currently, an email address is validated by the system during registration (by validating the domain portion).

If DNS is not available, is alternative implementation, or firewalled - the call fails and we consider the domain invalid.   Admin user cannot be created.

This is also complicated by a regex bug #2841  that exists within the current release 0.26.0 

It is possible to turn off this option. But it currently defaults to ON - which makes it impossible to create an admin under some situations.

Recommended to make validation default to OFF.

This affects both manual registrations and automated install (admin email set via ENV VARs).

**Comment by engelgabriel** [comment]
Set admin email set via ENV VARs is not affected anymore.

**Comment by engelgabriel** [comment]
You can set this `Accounts_UseDNSDomainCheck` config to `false` via ENV VARs on your initial setup if you are sure your server is blocked from outside world.

**Comment by TheReal1604** [comment]
It is possible to define the Env-VAR in the docker-compose file or it is only for manual installations without docker?

**Comment by engelgabriel** [comment]
AFAIK you can set ANY config of Rocket.Chat with ENV VAR. Juts use the same name as their _id on the settings collection. Also, it will only work on the initial setup, they will be ignored if they already have a value in the settings collection.

**Comment by TheReal1604** [comment]
@engelgabriel how to do it correct on first setup?
Tried it like this:

```
mongo:
  image: mongo
# volumes:
#    - ./data/runtime/db:/data/db
#    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:latest
# volumes:
#    - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=http://yourhost:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
    - **Accounts_UseDNSDomainCheck=false**
  links:
    - mongo:mongo
  ports:
    - 3000:3000
```

After recreating the docker containers it seems that this is not working. Or did i need a new mongodb container, too?
