### ISSUE TITLE
Fresh Docker install fail with Error creating users index 

### ISSUE THREAD

**Issue by imtrobin** [RocketChat/Rocket.Chat#29199]
Hi, I’m setting up a fresh install on RockyLinux 9 using docker, following instructions here

https://docs.rocket.chat/deploy/prepare-for-your-deployment/rapid-deployment-methods/docker-and-docker-compose

Docker runs fine, but when I access the logs, it show this error. Mongo logs look fine, it is default without password.

```
{“log”:“\n”,“stream”:“stderr”,“time”:“2023-04-29T09:11:11.012875203Z”}
{“log”:“/app/bundle/programs/server/node_modules/fibers/future.js:313\n”,“stream”:“stderr”,“time”:“2023-04-29T09:11:11.012965221Z”}
{“log”:“\u0009\u0009\u0009\u0009\u0009\u0009throw(ex);\n”,“stream”:“stderr”,“time”:“2023-04-29T09:11:11.012972635Z”}
{“log”:“\u0009\u0009\u0009\u0009\u0009\u0009^\n”,“stream”:“stderr”,“time”:“2023-04-29T09:11:11.012976401Z”}
{“log”:“errorClass [Error]: [An error occurred when creating an index for collection "users: getaddrinfo ENOTFOUND mongodb]\n”,“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261942114Z”}
{“log”:" at Collection.createIndex (packages/mongo/collection.js:801:15)\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261962073Z”}
{“log”:" at setupUsersCollection (packages/accounts-base/accounts_server.js:1776:9)\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261964983Z”}
{“log”:" at new AccountsServer (packages/accounts-base/accounts_server.js:75:5)\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261966848Z”}
{“log”:" at packages/accounts-base/server_main.js:7:12\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261968664Z”}
{“log”:" at module (packages/accounts-base/server_main.js:19:31)\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261970389Z”}
{“log”:" at fileEvaluate (packages/modules-runtime.js:336:7)\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261972082Z”}
{“log”:" at Module.require (packages/modules-runtime.js:238:14)\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261973728Z”}
{“log”:" at require (packages/modules-runtime.js:258:21)\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.26197541Z”}
{“log”:" at /app/bundle/programs/server/packages/accounts-base.js:2192:15\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261977166Z”}
{“log”:" at /app/bundle/programs/server/packages/accounts-base.js:2199:3\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261978868Z”}
{“log”:" at /app/bundle/programs/server/boot.js:369:38\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261980515Z”}
{“log”:" at Array.forEach (\u003canonymous\u003e)\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261982138Z”}
{“log”:" at /app/bundle/programs/server/boot.js:210:21\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261984149Z”}
{“log”:" at /app/bundle/programs/server/boot.js:423:7\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261985792Z”}
{“log”:" at Function.run (/app/bundle/programs/server/profile.js:256:14)\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261987426Z”}
{“log”:" at /app/bundle/programs/server/boot.js:422:13 {\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261989079Z”}
{“log”:" isClientSafe: true,\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261990717Z”}
{“log”:" error: ‘An error occurred when creating an index for collection "users: getaddrinfo ENOTFOUND mongodb’,\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.26199242Z”}
{“log”:" reason: undefined,\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261994216Z”}
{“log”:" details: undefined,\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261995789Z”}
{“log”:" errorType: ‘Meteor.Error’\n",“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261997398Z”}
{“log”:“}\n”,“stream”:“stderr”,“time”:“2023-04-29T09:11:11.261999022Z”}

```

**Comment by jw1892626** [comment]
Getting same error with fresh builds.  I think it is related to the volumes for mongodb.  Be sure they volumes are made and given correct permissions.  May need to delete them and recreate them.

**Comment by debdutdeb** [comment]
that's odd. Could you share the output of `docker compose config` in the same directory the compose file is in? did you change anything of the compose file?

**Comment by imtrobin** [comment]
I only changed BINDIP and ROOT_URL in .env.

docker file is from curl -L https://raw.githubusercontent.com/RocketChat/Docker.Official.Image/master/compose.yml -O

```
docker compose config
name: root
services:
  mongodb:
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: "true"
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: "27017"
      MONGODB_PORT_NUMBER: "27017"
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
    image: docker.io/bitnami/mongodb:5.0
    networks:
      default: null
    restart: always
    volumes:
    - type: volume
      source: mongodb_data
      target: /bitnami/mongodb
      volume: {}
  rocketchat:
    depends_on:
      mongodb:
        condition: service_started
    environment:
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ""
      MONGO_OPLOG_URL: mongodb://mongodb:27017/local?replicaSet=rs0
      MONGO_URL: mongodb://mongodb:27017/rocketchat?replicaSet=rs0
      PORT: "3000"
      REG_TOKEN: ""
      ROOT_URL: 192.168.2.231
    expose:
    - "3000"
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.rule: Host(``)
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.tls.certresolver: le
    networks:
      default: null
    ports:
    - mode: ingress
      host_ip: 192.168.2.231
      target: 3000
      published: "3000"
      protocol: tcp
    restart: always
networks:
  default:
    name: root_default
volumes:
  mongodb_data:
    name: root_mongodb_data
    driver: local
```
