### ISSUE TITLE
Nginx reverse proxy can't redirect correctly with custom location defined ever since update 6.2.0.

### ISSUE THREAD

**Issue by VLK14** [RocketChat/Rocket.Chat#29332]
### Description:

Nginx reverse proxy doesn't redirect some paths of Rocket.Chat correctly since version 6.2.0. 
On previous versions, Nginx with a location different from the default `/`redirected correctly without any problem. The Root URL was also configured with the location added at the end, and it worked as expected.

From versions  6.2.0 to  6.2.2, it only works for some paths, but for groups, channels and for some of the admin paths it stopped working. The problem is that location is not being added to the full path. 

I've tested with a different Root URL and location, changed the Root URL on MongoDB to make sure changes were being applied, but the problem persisted.
 
I'm using the default Nginx reverse proxy configuration provided by the official documentation, with the only change being the location.

Nginx version: `nginx/1.18.0`

### Steps to reproduce:

I'm attaching the docker-compose file and Nginx configuration used to testes this versions before implementing them on my production environment. Version 6.1.6 was the last version where this configuration worked as expected. Updating Rocket.Chat to version 6.2.0, 6.2.1 or 6.2.2 will result in the same behavior explained above.

+ docker-compose.yml

```
version: '3'

volumes:
  mongodb_data:
    driver: local
  rocketchat_uploads:
    driver: local

services:

  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.1.6
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: Host(`<IP>`)
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb27017/local?replicaSet=rs0"
      ROOT_URL: https://<IP>/RocketChat
      PORT: 3000
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: Debian
    volumes:
      - rocketchat_uploads:/app/uploads
    depends_on:
      - mongodb
    ports:
      - "127.0.0.1:3000:3000"

  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    restart: unless-stopped
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: "true"
      ALLOW_EMPTY_PASSWORD: "yes"
```

+ /etc/nginx/conf.d/nginx_settings.conf

```
server {
    listen 80;
    return  301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/server_cert.pem;
    ssl_certificate_key /etc/nginx/ssl/server_key.pem;
    ssl_client_certificate /etc/nginx/ssl/root-ca_cert.pem;
    ssl_dhparam /etc/nginx/ssl/dhparams.pem;
    ssl_protocols TLSv1.2;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:20m;
    ssl_session_timeout 180m;
    ssl_verify_client optional;

    client_max_body_size 1G;

    location /RocketChat {
        proxy_pass http://127.0.0.1:3000/RocketChat;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Nginx-Proxy true;
        proxy_redirect off;
    }
}

```

### Expected behavior:

Rocket.Chat would work as previously described, where it redirected correctly without having the need to add the location to the full path when accessing groups or channels.

### Actual behavior:

The location is not being added to the full URL path when redirecting to some specific locations, like groups and channels.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.2.0, 6.2.1, 6.2.2
- Operating System: Debian 11, 
- Kernel: 5.10.0-23-amd64
- Deployment Method: Docker
- Docker version: 20.10.5+dfsg1, build 55c4c88
- Number of Running Instances: 1
- DB Replicaset Oplog: Default
- NodeJS Version: 14.21.3
- MongoDB Version: 5.0

### Client Setup Information

This problem was been tested on a Linux machine (Ubuntu 22.04.2 LTS), with Web Browsers (Firefox, Chrome, Chromium) and the Snap Rocket.Chat application (version 3.8.13).
