### ISSUE TITLE
New Docker Installation having "The application GUI just crashed." in Setup Wizard

### ISSUE THREAD

**Issue by iamfasal** [RocketChat/Rocket.Chat#30495]
### Description:

I've deployed a latest new RocketChat instance using Docker Compose and the Setup Wizard is showing "Application Error
 The application GUI just crashed." . I tried loading from different browsers and even from private windows to rule out cache issues. I've used the below Docker Compose file to deploy the installation:

```
version: '3.4'
services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:6.3.7
    restart: always
    volumes:
      - ./data/uploads:/app/uploads
    environment:
      PORT: 3000
      ROOT_URL: "http://chat.mydomain.com:3000"
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM:-}
      REG_TOKEN: ${REG_TOKEN:-}

    depends_on:
      - mongodb
    ports:
      - 127.0.0.1:3000:3000


  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    restart: always
    volumes:
      - ./data/mongodb:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}
```

### Expected behavior:

The Setup Wizard should open correctly to proceed with the deployment, but it is not working in my case.

### Actual behavior:

Getting "Application Error  The application GUI just crashed." in Setup Wizard UI.

### Server Setup Information:

- Version of Rocket.Chat Server: 6.3.7
- Operating System: CentOS 7
- Deployment Method:  Docker
- Number of Running Instances: 1
- DB Replicaset Oplog: Yes
- NodeJS Version: The version in the Docker image
- MongoDB Version: 6.0

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Relevant logs:

I can see a lot of errors in the browser console about some Syntax errors and some modules not found. 
An example:

- setup-wizard:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
- Uncaught (in promise) Error: Cannot find module '/node_modules/hljs9/lib/languages/css.js'
    at y (c53f6e6……resource=true:3:644)
    at g (c53f6e6……esource=true:3:1030)
    at d.r [as require] (c53f6e6……esource=true:3:3658)
    at d.a [as link] (c53f6e6……esource=true:5:4691)
    at h (c53f6e6……ource=true:327:2055)
    at c53f6e6……source=true:327:881
    at c53f6e6……esource=true:1:8881
    at async s (c53f6e6……rce=true:522:175948)

etc.
