### ISSUE TITLE
moment-locales cannot be loaded after upgrading to 6.4.0

### ISSUE THREAD

**Issue by HanadaLee** [RocketChat/Rocket.Chat#30597]
### Description:

i18n fail to load in version 6.4.0
![image](https://github.com/RocketChat/Rocket.Chat/assets/33758411/348fa6a1-aed3-41e0-a4b1-f2b28ac769b8)

![image](https://github.com/RocketChat/Rocket.Chat/assets/33758411/cb9064f5-5d88-41cf-b25e-4cc234cc628e)

### Steps to reproduce:

upgrade to 6.4.0 docker image, and i18n will not load successfully.

When use 中文（中国），zh-CN，I will get:
TranslationProvider.tsx:118     GET https://rocketdomain.com/i18n/zh-CN.json 400 (Bad Request)

When I change to 中文，zh, I will get:
![image](https://github.com/RocketChat/Rocket.Chat/assets/33758411/d070ff72-70de-4e03-b0ab-1acd727c2f21)

### Server Setup Information:

- Version of Rocket.Chat Server: 6.4.0
- Operating System: Debian
- Deployment Method: docker
- Number of Running Instances: 
- DB Replicaset Oplog: 
- NodeJS Version:  
- MongoDB Version: 5.0

### Client Setup Information

- Desktop App or Browser Version: Google Chrome 117.0.5938.132
- Operating System: Windows 10

### Relevant logs:
```
MessageTypes.ts:20 MessageType.render is deprecated. Use MessageType.message instead. livechat_webrtc_video_call
registerType @ MessageTypes.ts:20
module @ messageTypes.ts:109
（匿名） @ verifyErrors.js:34
g @ url_common.js:80
r @ url_common.js:80
x @ verifyErrors.js:34
module @ index.ts:1
（匿名） @ verifyErrors.js:34
g @ url_common.js:80
r @ url_common.js:80
x @ verifyErrors.js:34
module @ importPackages.ts:1
（匿名） @ verifyErrors.js:34
g @ url_common.js:80
r @ url_common.js:80
x @ verifyErrors.js:34
（匿名） @ verifyErrors.js:34
（匿名） @ dynamics_browser.js:74
Promise.then（异步）
e.then @ verifyErrors.js:34
s.dynamicImport @ verifyErrors.js:34
（匿名） @ main.ts:12
（匿名） @ dynamics_browser.js:74
Promise.then（异步）
e.then @ verifyErrors.js:34
e @ main.ts:12
g @ url_common.js:80
r @ url_common.js:80
t @ url_common.js:80
（匿名） @ main.ts:15
TranslationProvider.tsx:247 Error loading moment locale: r {isClientSafe: true, error: undefined, reason: undefined, details: undefined, message: '[undefined]', …}details: undefinederror: undefinederrorType: "Meteor.Error"isClientSafe: truemessage: "[undefined]"reason: undefinedstack: "Error: [undefined]\n    at w._livedata_result (https://rocketchat-domain.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:92:19432)\n    at w.onMessage (https://rocketchat-domain.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:92:21790)\n    at d (/client/lib/meteorCallWrapper.ts:1:891)\n    at eval (/client/lib/meteorCallWrapper.ts:1:1031)\n    at https://rocketchat-domain.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:1:8769"[[Prototype]]: Error
eval @ TranslationProvider.tsx:247
（匿名） @ dynamics_browser.js:74
Promise.then（异步）
e.then @ verifyErrors.js:34
eval @ TranslationProvider.tsx:245
fk @ react-dom.production.min.js:270
exports.unstable_runWithPriority @ scheduler.production.min.js:26
gg @ react-dom.production.min.js:130
Oj @ react-dom.production.min.js:269
eval @ react-dom.production.min.js:269
V @ scheduler.production.min.js:24
F.port1.onmessage @ scheduler.production.min.js:20
SDKClient.ts:86 r {isClientSafe: true, error: 'not-allowed', reason: undefined, details: undefined, message: '[not-allowed]', …}details: undefinederror: "not-allowed"errorType: "Meteor.Error"isClientSafe: truemessage: "[not-allowed]"reason: undefinedstack: "Error: [not-allowed]\n    at n (https://rocketchat-domain.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:92:18922)\n    at w._livedata_nosub (https://rocketchat-domain.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:92:18994)\n    at w.onMessage (https://rocketchat-domain.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:92:21749)\n    at https://rocketchat-domain.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:62:2678\n    at Array.forEach (<anonymous>)\n    at c.forEachCallback (https://rocketchat-domain.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:62:3735)\n    at socket.onmessage (https://rocketchat-domain.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:62:2648)\n    at r.dispatchEvent (https://rocketchat-domain.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:62:8437)\n    at https://rocketchat-domain.com/8e05287ab767124f83312735e10877a4b56151ac.js?meteor_js_resource=true:62:18870\n    at Array.forEach (<anonymous>)"[[Prototype]]: Errorclone: ƒ ()constructor: ƒ ()[[Prototype]]: Object
onError @ SDKClient.ts:86
_livedata_nosub @ livedata_connection.js:1607
onMessage @ livedata_connection.js:1810
（匿名） @ browser.js:185
forEachCallback @ common.js:30
socket.onmessage @ browser.js:184
r.dispatchEvent @ sockjs-1.6.1-min-.js:2
（匿名） @ sockjs-1.6.1-min-.js:2
_._transportMessage @ sockjs-1.6.1-min-.js:2
s.emit @ sockjs-1.6.1-min-.js:2
ws.onmessage @ sockjs-1.6.1-min-.js:2
```

```
{"level":50,"time":"2023-10-26T18:07:25.077Z","pid":1,"hostname":"70b0611c17f7","name":"System","msg":"Exception while invoking method loadLocale","err":{"type":"Error","message":"Unknown asset: moment-locales/zh.js","stack":"Error: Unknown asset: moment-locales/zh.js<br>    at getAsset (/app/bundle/programs/server/boot.js:303:21)<br>    at Object.getTextAsync (/app/bundle/programs/server/boot.js:318:18)<br>    at server/lib/getMomentLocale.ts:7:17<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at packages/meteor.js:367:22<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)<br>    at packages/ddp-server/livedata_server.js:1818:36<br>    at new Promise (<anonymous>)<br>    at Server.applyAsync (packages/ddp-server/livedata_server.js:1817:12)<br>    at Server.callAsync (packages/ddp-server/livedata_server.js:1743:17)<br>    at app/api/server/v1/misc.ts:559:33<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/api/server/v1/misc.ts:559:17<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"}} 
```

![image](https://github.com/RocketChat/Rocket.Chat/assets/33758411/3b3dce4d-ef4e-439e-aca6-e7ae2412e158)

Most strings currently display English status using underscores, which really bothers me

**Comment by HanadaLee** [comment]
Is this related to this pull request?

https://github.com/RocketChat/Rocket.Chat/pull/30167

rocket.chat works just fine when I'm on 6.3.2

@tassoevan @yash-rajpal

**Comment by tassoevan** [comment]
I don't think I understand what is happening, since we never had a `zh-CN` translation... What am I missing, @HanadaLee?

**Comment by HanadaLee** [comment]
> I don't think I understand what is happening, since we never had a `zh-CN` translation... What am I missing, @HanadaLee?

I don’t know why zh-CN appears, but similar problems still occur after manually changing it to zh.

And even if I start a new instance using version 6.4.6, I have the same problem.

Here is my docker-compose

```
version: "3"

services:
  rocketchat:
    image: rocketchat/rocket.chat:6.4.6
    restart: unless-stopped
    container_name: rocketchat
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: Host(`${DOMAIN}`)
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
    environment:
      MONGO_URL: "${MONGO_URL:-\
        mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
          ${MONGODB_DATABASE:-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      MONGO_OPLOG_URL: "${MONGO_OPLOG_URL:\
        -mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
          local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      ROOT_URL: ${ROOT_URL:-http://localhost:${HOST_PORT:-3000}}
      PORT: ${PORT:-3000}
    depends_on:
      - mongodb
    expose:
      - 13008
    ports:
      - 127.0.0.1:13008:13008

  mongodb:
    image: bitnami/mongodb:5.0
    restart: unless-stopped
    container_name: rocketchat-mongodb
    volumes:
      - ./data/mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}
```
here is env file
```
DOMAIN=mydomain
MONGO_URL=mongodb://mongodb:27017/rocketchat?replicaSet=rs0
MONGO_OPLOG_URL=mongodb://mongodb:27017/local?replicaSet=rs0
ROOT_URL=https://mydomain
PORT=13008
DEPLOY_METHOD=docker
DEPLOY_PLATFORM=
REG_TOKEN=

MONGODB_REPLICA_SET_MODE=primary
MONGODB_REPLICA_SET_NAME=rs0
MONGODB_PORT_NUMBER=27017
MONGODB_INITIAL_PRIMARY_HOST=mongodb
MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
MONGODB_ADVERTISED_HOSTNAME=mongodb
MONGODB_ENABLE_JOURNAL=true
ALLOW_EMPTY_PASSWORD=yes

```

I used it to launch a completely new instance without any historical data. and it also have a same problem
![image](https://github.com/RocketChat/Rocket.Chat/assets/33758411/e16be886-7619-4ab3-929e-a12571d09693)
![image](https://github.com/RocketChat/Rocket.Chat/assets/33758411/a8d2b548-5317-4c17-8d61-103e72e492e8)

![image](https://github.com/RocketChat/Rocket.Chat/assets/33758411/964e9292-0a53-482d-9b59-adda7d03638a)

```
{"level":50,"time":"2023-11-16T06:39:11.506Z","pid":1,"hostname":"28c45a8b7268","name":"System","msg":"Exception while invoking method loadLocale","err":{"type":"Error","message":"Unknown asset: moment-locales/zh.js","stack":"Error: Unknown asset: moment-locales/zh.js\n    at getAsset (/app/bundle/programs/server/boot.js:303:21)\n    at Object.getTextAsync (/app/bundle/programs/server/boot.js:318:18)\n    at server/lib/getMomentLocale.ts:7:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at packages/meteor.js:367:22\n    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1389:31)\n    at packages/ddp-server/livedata_server.js:1818:36\n    at new Promise (<anonymous>)\n    at Server.applyAsync (packages/ddp-server/livedata_server.js:1817:12)\n    at Server.callAsync (packages/ddp-server/livedata_server.js:1743:17)\n    at app/api/server/v1/misc.ts:620:33\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40\n => awaited here:\n    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)\n    at app/api/server/v1/misc.ts:620:17\n    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40"}}

```
