### ISSUE TITLE
Docker support dropped?

### ISSUE THREAD

**Issue by EqualMarcus** [RocketChat/Rocket.Chat#31271]
Latest Docker release is 6.4.2, despite 6.4.8 existing.

Still no 6.5.0 Docker release either

No activity on the Docker Image RC repository

Could you update your documentation to show you've stopped support Docker? Or could you continue supporting Docker? Thanks!

**Comment by reetp** [comment]
Just updated an instance  using compose to 6.5.0 with no issues.

https://docs.rocket.chat/deploy/deploy-rocket.chat/deploy-with-docker-and-docker-compose

https://hub.docker.com/r/rocketchat/rocket.chat

OR select a specific release ([details of releases available](https://github.com/RocketChat/Rocket.Chat/releases)):

`docker pull rocketchat/rocket.chat:vX.X.X`

compose eg: 

```
services:
    rocketchat:
        image: rocketchat/rocket.chat:6.5.0
        container_name: rocketchat
        environment:
        - MONGO_URL=mongodb://127.0.0.1:27017/rocketchat?replicaSet=rs0
        - MONGO_OPLOG_URL=mongodb://127.0.0.1:27017/local?replicaSet=rs0
        - blah
        blahblah
```

Suggest this is closed NotABug
