### ISSUE TITLE
Always show scroll bars

### ISSUE THREAD

**Issue by audouts** [RocketChat/Rocket.Chat#31717]
**Is your feature request related to a problem? Please describe.**
It's really annoying trying to find the narrow, hidden scroll bars. The scroll bar on the chat window (right side) can be difficult to find, however the scroll bar on the channels/chat window (left side) is the bigger problem. I sometimes end up clicking on multiple conversations or channels before the scroll bar finally appears.

**Describe the solution you'd like**
An option in Settings to always show scroll bars.
Ideally, we could also have an option for narrow/wide bars but that is secondary.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by audouts** [comment]
It is also worth noting that RocketChat does not honor the scrollbar setting in Windows to disable hidden scrollbars.

**Comment by audouts** [comment]
> should i fix this issue by adding an option in the settings? any senior here ?

Can you help with this?

**Comment by crycode-de** [comment]
Since release 7.5.0 RocketChat is using OverlayScrollbars (#33796).
A workaround to always show the scrollbars is to add the following CSS to the *Custom CSS* in *Settings*->*Layout*:

```css
/*
 * Always show overlay scrollbars, not only while scrolling
 */
.os-scrollbar-vertical.os-scrollbar-auto-hide.os-scrollbar-auto-hide-hidden,
.os-scrollbar-horizontal.os-scrollbar-auto-hide.os-scrollbar-auto-hide-hidden {
  visibility: visible;
  opacity: 0.44;
}
```

If you want the vertical/horizontal scrollbars only be shown always, you may omit the other CSS selector from this snippet.
