### ISSUE TITLE
Port used by Rocket.Chat should be configurable

### ISSUE THREAD

**Issue by dohseven** [RocketChat/Rocket.Chat#3199]
Your Rocket.Chat version: 0.30

By default, the port used by Rocket.Chat is 3000. But other applications may need to use this particular port on the same server.
The exposed port should be customized through an option in order to chose the most adequate one.

**Comment by BirknerAlex** [comment]
Hello,

you can export the PORT as ENV variable to bind it to another one.
Just do this command before starting the server:

```export PORT=12345```

Regards,
Alexander

**Comment by geekgonecrazy** [comment]
I think using the environment variable with this one is probably the best approach here.  This way if you can set what port you want to use on start, vs someone changing it in the UI, and not being able to change it again

**Comment by dohseven** [comment]
Thank you for your quick answer. I tried it without being able to change the port. 

I use docker-compose to launch Rocket.Chat:
```
export PORT=4000
docker-compose up -d rocketchat
```

I saw that there are references to the the port 3000 in the `docker-compose.yml` file and I tried to update it here to, but it doesn't work. What am I missing?

**Comment by marceloschmidt** [comment]
Did you try changing all 3000 to another port in docker-compose.yml? That should suffice.

**Comment by dohseven** [comment]
Yes, I tried it, but it didn't work.

What worries me is that there seems to be a lot of hardcoded references to this 3000 port in the code, as [a simple search](https://github.com/RocketChat/Rocket.Chat/search?utf8=%E2%9C%93&q=3000) show it.

**Comment by geekgonecrazy** [comment]
@dohseven those found in the search are hard coded port numbers.  The few that are actually related to port are in configuration files for a few different deployment methods.  The other few are timeout values.  3000 milliseconds is 3 seconds. 

When changing the value inside the docker compose file you're going to need to change a few things.

```
rocketchat:
  image: rocketchat/rocket.chat:latest
# volumes:
#    - ./uploads:/app/uploads
  environment:
    - PORT={newport}
    - ROOT_URL=http://yourhost:{newport}
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - {newport}:{newport}
```

if you just simply want it to be on the host as a different port you can just change like this:

```
rocketchat:
  image: rocketchat/rocket.chat:latest
# volumes:
#    - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=http://yourhost:{newport}
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - {newport}:3000
```

Now internal to the container its still on 3000, but is bound to the host and listening on {newport}
