### ISSUE TITLE
Banner notification is not undone

### ISSUE THREAD

**Issue by wanderlage** [RocketChat/Rocket.Chat#32018]
### Description:

After updating to version 6.5.4 the banners are not disappearing.
You click close and nothing happens.

### Expected behavior:

Click the close button on the banner and it will disappear.

### Actual behavior:

![image](https://github.com/RocketChat/Rocket.Chat/assets/30476005/d9c205d3-ef6b-4974-a6af-3cd558c0c524)

### Server Setup Information:

- Version of Rocket.Chat Server:  6.5.4
- Operating System:  
- Deployment Method: docker
- Number of Running Instances: 1 
- NodeJS Version: v14.21.3
- MongoDB Version: 6.0.10 / wiredTiger (oplog Enabled)

### Client Setup Information

- Desktop App or Browser Version:
- Operating System:

### Additional context

Analyzing the rocketchat_banner_dismiss collection in the database, we can see that it updated the table, but the application did not consider it.

```
db.getCollection("rocketchat_banner_dismiss").find({})
```
```json
{
    "_id" : "65f82df54ff1b90ee957618d",
    "userId" : "ayywxy79Zay3AbGfa",
    "bannerId" : "65f81986b42c4ec42d29bc98",
    "dismissedBy" : {
        "_id" : "ayywxy79Zay3AbGfa",
        "username" : "wander.silva"
    },
    "dismissedAt" : ISODate("2024-03-18T12:05:09.209+0000"),
    "_updatedAt" : ISODate("2024-03-18T12:05:09.210+0000")
}
```

When clicking to close the notification, the error below is displayed in the server log.

### Relevant logs:
```
{"level":50,"time":"2024-03-18T15:02:14.485Z","pid":1,"hostname":"rocketchat-rocketchat-6dd4f946fd-9dxhw","name":"System","err":{"type":"CloudWorkspaceConnectionError","message":"Failed to connect to Rocket.Chat Cloud: undefined","stack":"CloudWorkspaceConnectionError: Failed to connect to Rocket.Chat Cloud: undefined<br>    at server/modules/core-apps/cloudAnnouncements.module.ts:255:10<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at server/modules/core-apps/cloudAnnouncements.module.ts:86:27<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","name":"CloudWorkspaceConnectionError"},"msg":"Failed to connect to Rocket.Chat Cloud: undefined"} 
```

**Comment by danielfariati** [comment]
We were also having this problem with version 6.5.
Tried updating to the latest version (6.6.3), to see if it would fix it, but the problem still persists.

**Comment by Visbhavesh** [comment]
I wanted to work in thus issue please Assign this issue to me.

**Comment by luizjr** [comment]
It takes a long time to resolve it, given that there are already people willing to resolve it. This problem has a very negative impact on the Rocketchat user experience.

**Comment by reetp** [comment]
> It takes a long time to resolve it, given that there are already people willing to resolve it. This problem has a very negative impact on the Rocketchat user experience.

There is a very long process involved in getting items fixed. It has to go through a number of stages and it competes with separate issues raised directly by (paying) Enterprise customers along with the requirements of various other teams.

If people want to fix it and add PRs then they can go right ahead but no one gets 'assigned' anything. 

Can the OP or anyone else confirm if this is still an issue?

**Comment by reetp** [comment]
> Can confirm still having this issue. Persistent banner that does not get dismissed. I've removed the element via custom CSS for now but obviously not a permanent solution.

Doing 'Me too' doesn't help as your situation may have a totally different cause from the OP.

Please fill out the Server setup and Client setup details from the bug template so we can see what you are running.

Note you should be testing this on minimum 6.8.0 or 6.9.0

Please also include the error messages from your log as per the OP.

Thanks.

**Comment by reetp** [comment]
I believe this might help fix some of these issues.

https://github.com/RocketChat/Rocket.Chat/pull/32552

Probably in 6.10

**Comment by Gustrb** [comment]
We probably shouldn't be returning error: undefined as well, I will talk with the team so we can fix that :)

**Comment by Gustrb** [comment]
https://github.com/RocketChat/Rocket.Chat/pull/32552 was merged so this will land on 6.10 😁

**Comment by func0der** [comment]
The problem still persists. No error in the logs. The requests goes through correctly (status code 200), the response is something like:

```json
{
    "type": "banner.close",
    "triggerId": "Qtkrxxxxx",
    "appId": "cloud-announcements-core",
    "viewId": "68867cxxxxx"
}
```

the banner stays open afterwards.

**Comment by luizjr** [comment]
> The problem still persists. No error in the logs. The requests goes through correctly (status code 200), the response is something like:
> 
> {
>     "type": "banner.close",
>     "triggerId": "Qtkrxxxxx",
>     "appId": "cloud-announcements-core",
>     "viewId": "68867cxxxxx"
> }
> the banner stays open afterwards.

Same problem here, every time you restart or update this problem comes back, and ends up making the rocket bad, crashing.

**Comment by reetp** [comment]
Please read this.

https://github.com/RocketChat/Rocket.Chat/issues/32018#issuecomment-2151949945

Please state your server setup or you will get ignored and nothing will get fixed.

**Comment by luizjr** [comment]
[rocketchat-rocketchat-97c49ff59-4rblk.log](https://github.com/user-attachments/files/21666414/rocketchat-rocketchat-97c49ff59-4rblk.log)

When I clear the banner table it stops crashing the instance, but if I don't do this it overflows memory and processor and enters a restart loop because of the livenessprobe

**Comment by reetp** [comment]
As per my previous, posting a proper server setup would get you help faster.

- Deployment type
- Licence
- Approximate number of users
- Proxy
- Firewall 

etc etc.

> Not required (running micro services)

Are you running EE? 

```
"msg":"Error during workspace sync"

"msg":"Failed to communicate with Rocket.Chat Cloud","url":"https://releases.rocket.chat/v2/server/supportedVersions"

```
You probably ought to check these as well. Your server needs to communicate to the outside world.

**Comment by luizjr** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/e49c9a54-d7cc-48d9-b202-9db7b9846379" />

**Comment by reetp** [comment]
Be a lot easier and much more searchable if you used text instead of screenshots........

If you want devs attention make it easy for them rather than having to squint and find information.

See [How to ask smart questions that will attract attention](https://gist.github.com/reetp/a66149d5f060f260643a353ca7067a98#still-stuck)

So please fill in the blanks:

- Version - 7.9.1
- Deployment type - docker etc?
- Licence - CE
- Approximate number of users - 250
- File storage - hopefully not GridFS?
- Proxy - nginx/traefik?
- Firewall - yes/no/more detail?
- https certificates?

Have you checked why your server can't connect online as I suggested?

**Comment by luizjr** [comment]
Version - 7.9.1
Deployment type - Helm Chart
Licence - CE
Approximate number of users - 250
File storage - S3
Proxy - nginx
Firewall - no
https certificates: yes managed by nginx ingress

I'll check if there's remote access to the rocket cloud, but it's strange that when it times out it consumes a lot of resources, and it should go to the rocketchat cloud if in theory it's looking for banner information, wouldn't it be in the internal database?

**Comment by reetp** [comment]
> I'll check if there's remote access to the rocket cloud

I'd eliminate that first. There shoudl be zero connectivity issues.

Why details matter:

> ReplicaSet OpLog: Not required (running micro services)
> Licence - CE

I'm not sure you can run microservices under CE these days. It is a EE only feature?

https://docs.rocket.chat/v1/docs/microservices

I'd suggest you check this and if it has any effect on your setup.

I'll see if I can ask for a comment from someone who knows more than me.

**Comment by luizjr** [comment]
I switched to microservices to reduce outages, and it really helped. I realized it allows me to run like this, but it doesn't allow replicas because when I deploy a replica, it doesn't deploy the second one. However, I've already switched to this format because it's crashing more frequently without being a microservice.

If you prefer, I can switch it out of microservices mode and monitor the logs and send them here.

**Comment by eisberg** [comment]
Is there any news?

I have a similar problem with this banner. 
Deleting data from rocketchat_banner_dismiss and rocketchat_banner in mongodb temporarily helps, but after a while the problem comes back again.

**Comment by reetp** [comment]
> Is there any news?

Please read my previous comments above.

**Comment by eisberg** [comment]
Version - 7.9.3
Deployment type - docker
Licence - CE
Approximate number of users - 50
File storage - FileSystem
Proxy - nginx
Firewall - no
https certificates - letsencrypt
MongoDB 7.0.15 / wiredTiger (oplog enabled)

docker-compose.yaml
```yaml
services:
  rocketchat:
    image: rocketchat/rocket.chat:${RELEASE:-latest}
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: Host(`${DOMAIN:-}`)
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
    volumes:
         - ./uploads:/app/uploads
    environment:
      MONGO_URL: "${MONGO_URL:-\
        mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        ${MONGODB_DATABASE:-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      MONGO_OPLOG_URL: "${MONGO_OPLOG_URL:\
        -mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      ROOT_URL: ${ROOT_URL:-http://localhost:${HOST_PORT:-3000}}
      PORT: ${PORT:-3000}
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM:-}
      REG_TOKEN: ${REG_TOKEN:-}
    depends_on:
      - mongodb
    expose:
      - ${PORT:-3000}
    ports:
      - "${BIND_IP:-0.0.0.0}:${HOST_PORT:-3000}:${PORT:-3000}"
  mongodb:
    image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-5.0}
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb
      - ./mongo_backup:/backup:rw
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes} 
```
