### ISSUE TITLE
MongoDB Fails to Initialize: "Illegal Instruction" Error with Bitnami MongoDB Image

### ISSUE THREAD

**Issue by vawaver** [RocketChat/Rocket.Chat#33495]
### MongoDB Fails to Initialize: "Illegal Instruction" Error with Bitnami MongoDB Image

**Description:**
I encountered an issue when deploying MongoDB using the Bitnami MongoDB Docker image in a Docker Compose setup. The system throws an "Illegal instruction" error during MongoDB initialization, preventing the service from starting.

**System Details:**
- **CPU:** Intel(R) Core(TM) i5-10400F (supports AVX)
- **OS:** Ubuntu Server 24.04
- **Docker:** Latest version
- **Rocket.Chat version:** Latest (`rocket.chat:${RELEASE:-latest}`)
- **MongoDB version:** Bitnami MongoDB 5.0

**Error Logs:**
```bash
mongodb 14:24:27.12 INFO  ==> Initializing MongoDB...
mongodb 14:24:27.27 INFO  ==> Deploying MongoDB from scratch...
/opt/bitnami/scripts/libos.sh: line 346:    47 Illegal instruction     (core dumped) "$@" > /dev/null 2>&1
```

**docker-compose.yml File:**
```yaml
volumes:
  mongodb_data: { driver: local }

services:
  rocketchat:
    image: rocket.chat:${RELEASE:-latest}
    restart: on-failure
    environment:
      MONGO_URL: "${MONGO_URL:-mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/${MONGODB_DATABASE:-rocketchat}?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      MONGO_OPLOG_URL: "${MONGO_OPLOG_URL:-mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      ROOT_URL: ${ROOT_URL:-http://localhost:${HOST_PORT:-3000}}
      PORT: ${PORT:-3000}
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

  mongodb:
    image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-5.0}
    restart: on-failure
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}
```

**What I Have Tried:**
- Verified that my CPU supports AVX, as MongoDB 5.0+ requires AVX instructions.
- Ensured all components (OS, Docker, and Docker Compose) are up to date.
- Attempted using a different MongoDB image, but the issue persists.

**Request:**
Can anyone provide insight into why the "Illegal instruction" error is happening during MongoDB initialization? Since my processor supports AVX, I'm unsure why this error persists, and I'm seeking guidance to resolve this.
