### ISSUE TITLE
Cannot read property 'collectionName' of undefined

### ISSUE THREAD

**Issue by e78908b943c8** [RocketChat/Rocket.Chat#3391]
Your Rocket.Chat version: 0.26.0, 0.31.0
Hi there.

I've been running version 0.26.0 for a couple weeks now and I started getting the following error yesterday.

![image](https://cloud.githubusercontent.com/assets/7596842/15630364/ffd83072-2572-11e6-8905-90a5d23163e1.png)

Given `auto-restart` in `docker-compose.yml` it restarts right after the error but it immediately goes down again.

I updated the version to 0.31.0 but the problem still persists
![image](https://cloud.githubusercontent.com/assets/7596842/15630359/e68fac3a-2572-11e6-84d0-81aa1be7e870.png)

**Comment by e78908b943c8** [comment]
docker-compose.yml
```
mongo:
  image: mongo
  volumes:
     - ./data/runtime/db:/data/db
     - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:0.31.0
  volumes:
     - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=http://yourhost:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 3000:3000
  restart: on-failure

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=GENERAL
    - ROCKETCHAT_USER=bot
    - ROCKETCHAT_PASSWORD=botpassword
    - BOT_NAME=bot
# you can add more scripts as you'd like here, they need to be installable by npm
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080 
```

**Comment by e78908b943c8** [comment]
docker-compose.yml
```
mongo:
  image: mongo
  volumes:
     - ./data/runtime/db:/data/db
     - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

rocketchat:
  image: rocketchat/rocket.chat:0.31.0
  volumes:
     - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=http://yourhost:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 3000:3000
  restart: on-failure

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat
  environment:
    - ROCKETCHAT_URL=rocketchat:3000
    - ROCKETCHAT_ROOM=***
    - ROCKETCHAT_USER=***
    - ROCKETCHAT_PASSWORD=***
    - BOT_NAME=bot
# you can add more scripts as you'd like here, they need to be installable by npm
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080 
```
