### ISSUE TITLE
matrix federation bridge does not start after update to 7.2.1

### ISSUE THREAD

**Issue by individual-it** [RocketChat/Rocket.Chat#34984]
### Description:

After updating from 7.1.0 to 7.2.0 the matrix federation stopped working and the matrix federation verification says that the bridge is not started yet.

### Steps to reproduce:

1. setup matrix federation with 7.1.0
2. update to 7.2.1
3. go to matrix federation settings (admin/settings/Federation) and click the Verify button

### Expected behavior:

verification should work

### Actual behavior:

verification says the bridge is not running

### Server Setup Information:

- Version of Rocket.Chat Server: 7.2.1
- License Type: Starter
- Number of Users: 
- Operating System: Ubuntu
- Deployment Method: docker
- Number of Running Instances: 1
- NodeJS Version: 
- MongoDB Version:

docker file:
```
services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:7.2.1
      #image: rocket.chat:latest
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./data/synapse/registration.yaml:/app/matrix-federation-config/registration.yaml
    environment:
      - PORT=3000
      - ROOT_URL=http://chat.jankari.tech
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.email
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 3300:3300

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/dump
    command: >
      env
      bash -c
        "while [ ! -f /data/db/WiredTiger ]; do
          echo \"wiredTiger migration hasn't started yet. Waiting 30 secs...\";
          sleep 30;
        done;
        docker-entrypoint.sh mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger;"
    depends_on:
      - migrator
    labels:
      - "traefik.enable=false"

  migrator:
    build: ./docker/
    volumes:
      - ./data/db:/data/db

    synapse:
    restart: always
    image: matrixdotorg/synapse:v1.121.1
    environment:
      SYNAPSE_CONFIG_DIR: "/data"
      SYNAPSE_CONFIG_PATH: "/data/homeserver.yaml"
    depends_on:
      - rocketchat
    ports:
      - 8008:8008
    volumes:
      - ./data/synapse:/data

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

homeserver.yaml 
```
# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "chat.jankari.tech"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
database:
  name: sqlite3
  args:
    database: /data/homeserver.db
log_config: "/data/chat.jankari.tech.log.config"
media_store_path: /data/media_store
registration_shared_secret: "xxxxxxxxxxxxxxxxxxxx"
report_stats: true
macaroon_secret_key: "xxxxxxxxxxxxxxxxx"
form_secret: "xxxxxxxxxxxxxxxxx"
signing_key_path: "/data/chat.jankari.tech.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"

app_service_config_files:
  - /data/registration.yaml
auto_accept_invites:
    enabled: true
use_appservice_legacy_authorization: true 
```

registration.yaml
```
id: rocketchat_xxxxx
hs_token: xxxxxxxxxxxx
as_token: xxxxxxxxxxxx
url: http://rocketchat:3300
sender_localpart: rocket.cat
namespaces:
  users:
    - exclusive: false
      regex: .*
  rooms:
    - exclusive: false
      regex: .*
  aliases:
    - exclusive: false
      regex: .*
de.sorunome.msc2409.push_ephemeral: false
use_appservice_legacy_authorization: true
rocketchat:
  homeserver_url: https://matrix.jankari.tech
  homeserver_domain: chat.jankari.tech
```

This configuration works fine with 7.1.1 but not with 7.2.1
