### ISSUE TITLE
Building isolated-vm in RC 7.3.0 package fails with GLIBC_2.29 version error

### ISSUE THREAD

**Issue by Gummikavalier** [RocketChat/Rocket.Chat#35084]
### Description:

I've created a support ticket about this, so this is just a stub in Github for those who may hit this and report the same.
I'll update here the resolution we have to take. (Which may include upgrading the OS.)

### Steps to reproduce:

1. RHEL 8 setup
2. Download RC tar from official source
3. Update to n 22.11.0 as required by RC 7.3.0
4. Proceed with npm install as usual
### Expected behavior:

RC builds nicely

### Actual behavior:

Building isolated-vm fails with error:
```
npm error prebuild-install warn install /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /rocketchat/programs/server/npm/node_modules/isolated-vm/out/isolated_vm.node)
```

### Server Setup Information:

- Version of Rocket.Chat Server: 7.3.0
- License Type: Enterprise
- Number of Users: 500+
- Operating System: RHEL 8
- Deployment Method: tar
- Number of Running Instances: 4
- DB Replicaset Oplog:  Yes
- NodeJS Version: 22.11.0
- MongoDB Version: 6.0

### Additional context

- There are no issues in building RC 7.2.1 with nodejs 20.18.0.

### Relevant logs:

-

**Comment by reetp** [comment]
Seen this with an Ubuntu box recently.

`ldd --version`

Yours will not support 7.3 at a guess. Something changed simewhere. 

OS upgrade required.

It's the reason I finally gave up and moved to docker....

Please updste if there is news. This should have been a breaking change....

**Comment by Gummikavalier** [comment]
I got the expected response from support that we should update glibc to 2.29.

Since I'm not a fan of container based (any other issues on top of everything), it is time to upgrade to RHEL 9.

**Comment by mddvul22** [comment]
Very disappointing that RC can't support RHEL 8.

**Comment by reetp** [comment]
> I got the expected response from support that we should update glibc to 2.29.

I suspected. I have said quite bluntly that this attitude is unprofessional. There should at least be a breaking notice.

That is inexcusable. 

> Since I'm not a fan of container based any other issues (on top of everything), it is time to upgrade to RHEL 9.

Me neither, but since I took the plunge I have had a much easier life. 

I still run a local mongo. Works very satisfactorily. I'd take a look. We're all being forced that way..... (Snaps - over my dead body.... !!)

**Comment by reetp** [comment]
> Very disappointing that RC can't support RHEL 8. 

I'm sure it is specifically Rocket or more likely the deps they use.

Yup I hate "rapid release, ever Alpha, must have latest even if it breaks your whole company" nonsense too.

**Comment by Gummikavalier** [comment]
I have to say it is not completely trivial to switch to docker-compose based RC setup from existing RPM based mongodb and tar based RC installation on RHEL8.

Podman should be used on RHEL so many tutorials go out of the window and for instance this is not much of use:
https://docs.rocket.chat/docs/deploy-with-docker-docker-compose

The issues begin pretty much immediately when the container cannot connect to mongodb that has been set to listen in localhost alone and get networking working at all _out_ from the container.

I will learn but I just had to vent this out. 😣

**Comment by reetp** [comment]
> I have to say it is not completely trivial to switch to docker-compose based RC setup from existing RPM based mongodb and tar based RC installation on RHEL8.

I still use a local rpm Mongo + Rocket in Docker for precisely these reasons.

It should not be that hard - it's only a dump and restore with Mongo?

> Podman should be used on RHEL so many tutorials go out of the window and for instance this is not much of use:
https://docs.rocket.chat/docs/deploy-with-docker-docker-compose

Like it or not, as far as Rocket go it is not a supported option....  Whether they'll add podman docs I don't know but I tried podman for a bit and then dumped it and went back to docker because of lots of hissy fits. And if we dump Rocky eventually....

> I will learn but I just had to vent this out. 😣

Yup..... been there, done that ;-)

I would seriously look at JUST dockerising Rocket. I personally run it in host mode - not bridged - and it was worked fine on my Cent boxes (and now moving to Rocky)

**Comment by Gummikavalier** [comment]
Thanks for advice. 😄 I'll take that as my aim.

Podman failed but dockerized RC node I got running. I'm still figuring out those network modes as access to RPM hosted mongo seems to fail. Failure is the best teacher. :\

**Comment by reetp** [comment]
> Thanks for advice. 😄 I'll take that as my aim.

🤣 

For ref my current compose:

```
version: '2'
services:
  rocketchat:
    image: rocketchat/rocket.chat:7.2.1
    container_name: rocketchat
    environment:
    - MONGO_URL=mongodb://127.0.0.1:27017/rocketchat?replicaSet=rs0
    - MONGO_OPLOG_URL=mongodb://127.0.0.1:27017/local?replicaSet=rs0
    - ROOT_URL=https://chat.mydomain.co.uk
    - MAIL_URL=smtp://127.0.0.1:25
    - HTTP_FORWARDED_COUNT=1
    network_mode: "host"
    volumes:
    - /opt/uploads/:/opt/uploads/
    restart: on-failure:2
    mem_limit: 4096MB
```

and

grep "^[^#;]"  /etc/mongod.conf

```

systemLog:
  verbosity: 0
  destination: file
  logAppend: true
  logRotate: reopen
  path: /var/log/mongodb/mongod.log
storage:
  dbPath: /var/lib/mongo
processManagement:
  fork: true  # fork and run in background
  pidFilePath: /var/run/mongodb/mongod.pid  # location of pidfile
  timeZoneInfo: /usr/share/zoneinfo
net:
  port: 27017
  bindIp: 127.0.0.1  # Enter 0.0.0.0,:: to bind to all IPv4 and IPv6 addresses or, alternatively, use the net.bindIpAll setting.
replication:
 replSetName: rs0
```

When Rocket is in host mode it runs as effectively another service just like say SMTP etc. despite it being in a container. As such it has easy access to any other service on the server.

Stops docker messing with your firewall too.

HTH.
