### ISSUE TITLE
Update docker-compose.yml to add SSL and ReplicaSet

### ISSUE THREAD

**Issue by engelgabriel** [RocketChat/Rocket.Chat#4243]

**Comment by wargamesqcf** [comment]
might also want to do this, so we can easily upload our own scripts.

```
hubot:
  image: rocketchat/hubot-rocketchat:v1.0.3
  volumes:
    - ./scripts:/home/hubot/scripts
```
