### ISSUE TITLE
HA - MongoDB and RocketChat Setup

### ISSUE THREAD

**Issue by TheReal1604** [RocketChat/Rocket.Chat#4299]
Your Rocket.Chat version: latest (0.39.0)

Hey guys,

i create a 2 Node setup with docker and a openstack HA proxy in front of these two.

The mongodb is a docker-container on both nodes in a replicaset. I created all users (admins, rocket (the user for rocket.chat, oplogger)

Now, i create rocket.chat docker containers with the following docker-compose config:

```
rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - PORT=3000
    - ROOT_URL=https://chat.domain.de
    - MONGO_URL=mongodb://rocket:password@rocket-1:27017,rocket-2:27017/rocketchat?replicaSet=rs0&readPreference=nearest&w=majority
    - MONGO_OPLOG_URL=mongodb://oplogger:password@rocket-1:27017,rocket-2:27017/local?authSource=admin&replicaSet=rs0
  ports:
    - 3000:3000
  extra_hosts:
    - "rocket-1:10.250.250.13"
    - "rocket-2:10.250.250.14"
```

My issue is now, the messages send are not displayed directly if you are connected to a different node, the user have to refresh the browser to see all other messages send to the other node. I checked https://github.com/RocketChat/Rocket.Chat.Docs/issues/68 already, but didnt get a hint to the right step to accomplish this.

I have tested the access without the load-balancer in front:
- Opening node1 rc instance in browser1
- Opening node2 rc instance in browser2
- Authenticate on both with the same user
- write a message on node1
-> message not shown on node2 until i reload the site in browser2

The websocket are established correctly, too. 

Anyone have a suggestion?

Edit: I checked also this documentation: https://rocket.chat/docs/installation/manual-installation/ubuntu/ -> no success
