### ISSUE TITLE
[Help] I need a CSS wizzard

### ISSUE THREAD

**Issue by bott0r** [RocketChat/Rocket.Chat#4408]
I really like the compact mode of RC and wonder if someone could help me with some reordering.
Unfortunately i am illiterate when it comes to CSS

I'd like to simply reorder the appearance of the message feed.
Richt now it is:
**{avatar}{name}{@user){Usertag}{time}{editsymbol} by {avatar if edited}{settingssymbol} {message}**

I would like to get it shorten down quite a bit
**{time}{avatar}{name}{editsymbol}{message}**

**Comment by lucasvanhalst** [comment]
You can hide the user tags in the settings so that's one part of it. 

to hide the `@user` and bot tag:
```css
.compact .message .user.user-card-message{
    display:none;
}
.compact .message .info .is-bot, .theme-night .message .info .role-tag{
   display:none;
}
```
The rest I don't have time for atm :P
