### ISSUE TITLE
After upgrade to 0.47.x (latest) connection refused.

### ISSUE THREAD

**Issue by lhaig** [RocketChat/Rocket.Chat#5190]
Your Rocket.Chat version: 0.47.0

Today I wanted to update to the latest version of the docker images. We were running 0.45 before.

After the upgrade I watched the db migrations happen and it is sitting at 0.69

```
[root@docker-compose-server rocketchat]# /usr/local/bin/docker-compose -f rocketchat.yml up --force-recreate --no-deps rocketchat
Recreating rocketchat_rocketchat_1
Attaching to rocketchat_rocketchat_1
rocketchat_1          | Updating process.env.MAIL_URL
rocketchat_1          | ufs: permissions are not defined for store "fileSystem"
rocketchat_1          | ufs: permissions are not defined for store "fileSystem"
rocketchat_1          | {"line":"160","file":"rocketchat_migrations.js","message":"Migrations: Not migrating, already at version 69","time":{"$date":1481572667307},"level":"info"}
rocketchat_1          | Updating process.env.MAIL_URL
rocketchat_1          | Using FileSystem for custom emoji storage
```

For now I run all the containers on the same host

````
rocketchat:
  image: rocketchat/rocket.chat:latest

  volumes:
    - /mnt/mongodb/uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=http://x.x.x.x:3000
    - MONGO_URL=mongodb://mongo:27017/rocketchat
    - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    - MAIL_URL=smtp://x.x.x.x
    - Accounts_UseDNSDomainCheck=false
    - HTTP_PROXY=http://x.x.x.x:3128
    - HTTPS_PROXY=http://x.x.x.x:3128
  links:
    - mongo:mongo
  ports:
    - 3000:3000

mongo:
  image: mongo:3.2
  volumes:
    - /mnt/mongodb/db:/data/db
    - /mnt/mongodb/dump:/dump
    - /mnt/mongodb/emoji:/tmp/emoji
  command: mongod --smallfiles --oplogSize 128 --replSet rs0

mongo-init-replica:
  image: mongo:3.2
  command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
  links:
    - mongo:mongo

# hubot, the popular chatbot (add the bot user first and change the password before starting this image)
hubot:
  image: rocketchat/hubot-rocketchat:latest
  environment:
    - ROCKETCHAT_URL=x.x.x.x
    - ROCKETCHAT_ROOM=''
    - ROCKETCHAT_USER=hubot
    - ROCKETCHAT_PASSWORD=hhhhhhhhhh
    - LISTEN_ON_ALL_PUBLIC=true
    - BOT_NAME=hubot
    - RESPOND_TO_DM=true
    - RESPOND_TO_EDITED=true
    #- REDIS_URL=
    - HTTP_PROXY=http://x.x.x.x:3128
    - HTTPS_PROXY=http://x.x.x.x:3128
# you can add more scripts as you'd like here, they need to be installable by npm
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics,hubot-http-status,hubot-standup-alarm,hubot-tell,hubot-plusplus,hubot-pugme,hubot-thank-you,hubot-rules
    #- EXTERNAL_SCRIPTS=hubot-help, hubot-seen, hubot-weather, hubot-hackerman, hubot-links, hubot-greetings, hubot-tell, hubot-geo, hubot-decides, hubot-praise, hubot-hello-ninja, hubot-thank-you, hubot-cool-ascii-faces,hubot-insulter,hubot-reddit
  links:
    - rocketchat:rocketchat
  volumes:
    - /mnt/mongodb/scripts:/home/hubot/scripts
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080
````

I keep getting connection refused from my nginx host running in a separate container on a separate host.

where can I start looking at if the rocket server has tsrated within the container.
