### ISSUE TITLE
Not receiving verification mails

### ISSUE THREAD

**Issue by AxxiD** [RocketChat/Rocket.Chat#5192]
RocketChat Version: **0.46.0** (Docker Image on Ubuntu 16.04.1 LTS)

### What I did:
1. I set up my rocket.chat server via docker-compose with MAIL_URL and without MAIL_URL.
2. I registered myself and set up SMTP and enabled email verification
3. I restarted the server
4. I registered a new account for test purpose.
5. I used the "Mailer" component to send all useres an email.

### What happened:
to 4: I did not receive any email.
to 5: I received all mails correctly for every account (even unverified ones).

### Config and Logs:
Here is my **docker-composer.yml**:
```
db:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://chat.my-domain.com/
    - Accounts_UseDNSDomainCheck=True
    - MAIL_URL=smtp://no-reply@my-domain.com:mypass@my-domain.com:465/
  links:
    - db:db
  ports:
    - 3000:3000
```

Here is an excerpt from the **mail.log** from the moment the verification email should have been sent:
```
2016-12-12 21:09:56 postfix/smtps/smtpd[10938]: connect from unknown[172.17.0.3]
2016-12-12 21:09:56 postfix/smtps/smtpd[10938]: lost connection after MAIL from unknown[172.17.0.3]
2016-12-12 21:09:56 postfix/smtps/smtpd[10938]: disconnect from unknown[172.17.0.3] ehlo=1 auth=1 mail=0/1 commands=2/3
```

I'm not sure if #3602 is related to this or not. Also I'm not sure if this is a bug or just a wrong configuration on my side.
