### ISSUE TITLE
[failed upgrade] Downgrading?

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#6207]
Rocket.Chat Version:  0.52.0

I just upgraded to version `0.53.0` but when I check the status it shows that the application is restarting itself infintively, as per:
> Restarting (1) 4 seconds ago

What is the best possible way to downgrade to `0.52.0`? I am using docker (to be specific: `docker-compose`).

The contents of my `docker-compose.yml` looks like this:
```
mongo:
  image: mongo
# volumes:
#    - ./data/runtime/db:/data/db
#    - ./data/dump:/dump
  command: mongod --smallfiles --oplogSize 128

chat:
  image: rocketchat/rocket.chat:latest
# volumes:
#    - ./uploads:/app/uploads
  environment:
    - PORT=3000
    - ROOT_URL=https://k0nsl.org
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 3000:3000
  restart: always
```

Do I just specify it like so: `image: rocketchat/rocket.chat:0.52.0`?

I do not have time to debug it as this was on a 'production' system 😁

[**EDIT:** _I just tried my own suggestion and it appears to have reverted back successfully. I've no idea why `0.53.0` didn't work and I am sorry that I cannot debug it on that system -- but I doubt I'll be the only one with this problem._]
