### ISSUE TITLE
Rocket.Chat on Alpine?

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#6524]
I'd like to inquire about people who run Rocket.Chat on Alpine Linux via Docker. I have just given it a spin and my attempts have been futile so far.

The Rocket.Chat container is just restarting itself endlessly. I am using the default `docker-compose.yml` file referred to in the documentation.

# Relevant information:
```
panzer:~/Rocket.Chat# docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                                    PORTS               NAMES
81908d55fe65        rocketchat/rocket.chat:latest   "node main.js"           3 minutes ago       Restarting (139) Less than a second ago                       rocketchat_rocketchat_1
b1eafbc99955        mongo:3.2                       "docker-entrypoint..."   3 minutes ago       Up 9 seconds                              27017/tcp           rocketchat_mongo_1
```
```
panzer:~/Rocket.Chat# free -m -h
             total       used       free     shared    buffers     cached
Mem:          2045        231       1813          0          6        120
-/+ buffers/cache:        104       1940
Swap:         2131          0       2131
```
```
panzer:~/Rocket.Chat# uname -a
Linux panzer 4.9.17-0-virtgrsec #1-Alpine SMP Thu Mar 23 10:13:45 GMT 2017 x86_64 Linux
```
```
panzer:~/Rocket.Chat# docker -v
Docker version 17.03.0-ce, build v17.03.0-ce
```

This is the reference `docker-compose.yml` I've been trying to use:
```
version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - MAIL_URL=smtp://smtp.email
      - HTTP_PROXY=http://proxy.domain.com
      - HTTPS_PROXY=http://proxy.domain.com
    depends_on:
      - mongo
    ports:
      - 3000:3000
    labels:
      - "traefik.backend=rocketchat"
      - "traefik.frontend.rule=Host: your.domain.tld"

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
     #- ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    labels:
      - "traefik.enable=false"

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:3.2
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo

  # hubot, the popular chatbot (add the bot user first and change the password before starting this image)
  hubot:
    image: rocketchat/hubot-rocketchat:latest
    restart: unless-stopped
    environment:
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_ROOM=GENERAL
      - ROCKETCHAT_USER=bot
      - ROCKETCHAT_PASSWORD=botpassword
      - BOT_NAME=bot
  # you can add more scripts as you'd like here, they need to be installable by npm
      - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-diagnostics
    depends_on:
      - rocketchat
    labels:
      - "traefik.enable=false"
    volumes:
      - ./scripts:/home/hubot/scripts
  # this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
    ports:
      - 3001:8080

  #traefik:
  #  image: traefik:latest
  #  restart: unless-stopped
  #  command: traefik --docker --acme=true --acme.domains='your.domain.tld' --acme.email='your@email.tld' --acme.entrypoint=https --acme.storagefile=acme.json --defaultentrypoints=http --defaultentrypoints=https --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS.Certificates:'
  #  ports:
  #    - 80:80
  #    - 443:443
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
```

Any ideas what could be going on and are there any Rocket.Chat Alpine users here who might be able to hint me into the right direction?

Any help is appreciated! 👍
