### ISSUE TITLE
High-Availability using Docker for Rocket.Chat?

### ISSUE THREAD

**Issue by k0nsl** [RocketChat/Rocket.Chat#6619]
Hello friends,

I wanted to experiment today with high-availability for my deployed Rocket.Chat. I went through the available documentation, but there exists no documentation for high-availability with Docker. Basically I want to accomplish what is written here:
https://rocket.chat/docs/installation/manual-installation/multiple-instances-to-improve-performance/

For this experiment I wanted to only use two virtual servers; a "main instance" and a secondary one, located in a different data center.

My current `docker-compose.yml` looks like this (nothing out of the ordinary):
```
root@juergen:~/rocket.chat# cat docker-compose.yml
mongo:
  image: mongo
  command: mongod --smallfiles --oplogSize 128
  restart: always

chat:
  image: rocketchat/rocket.chat:latest
#  image: rocketchat/rocket.chat:0.54.2
  environment:
    - PORT=3000
    - ROOT_URL=https://k0nsl.org
    - MONGO_URL=mongodb://mongo:27017/rocketchat
  links:
    - mongo:mongo
  ports:
    - 3000:3000
  restart: always
root@juergen:~/rocket.chat#
```

Can somebody drop some hints for me in order to get me started? I would experiment on my own, but if somebody already has a working solution, that'd be much better, of course.

Any advice and/or help is welcome.
