### ISSUE TITLE
Gracefully reconnect to mongodb

### ISSUE THREAD

**Issue by LarsKumbier** [RocketChat/Rocket.Chat#7246]
When running rocket.chat in any cloud environment (in my example kubernetes), a mongodb-server might take up some time until it's available. This has also lead to some issues here with docker-compose. Instead of failing right away, there should be an option to just retry a mongodb-connection for a specific period of time with an appropriate commandline and configuration argument like "retryMongoConnection=15". This would retry a mongodb-connection every second for at most 15 seconds.

**Comment by localguru** [comment]
similar problem with pm2

 https://rocket.chat/docs/installation/manual-installation/pm2-systemd-upstart

I set 
```
[Service]
ExecStartPre=/bin/sleep 3
```
to wait three seconds before starting RC, because the replica set needs some time be become ready (
MongoError: no primary found in replicaset)

**Comment by LarsKumbier** [comment]
yeah, I also solve it by setting `command: bash -c "sleep 15 && rocketchat..."`, but that is not a solution. A mongodb or anything between mongo and rocket.chat might hickup from time to time.

**Comment by sampaiodiego** [comment]
since this is a Meteor thing, there is no much we can do..

you should guarantee on your end that rocket.chat's services starts after mongodb.. 

@geekgonecrazy is there a way on kubernetes to wait a service to up? I know you can do it on `docker-compose` using [depends_on](https://docs.docker.com/compose/compose-file/#depends_on)

**Comment by geekgonecrazy** [comment]
If you deploy rocket.chat as a deployment in kubernetes it will try to schedule a pod for that deployment more than once.

@larskumbier how are you deploying on kubernetes?

**Comment by LarsKumbier** [comment]
`depends_on` does not work properly, because it doesn't have health- or availability-checks. You can get around that by providing your own entrypoint and checking for the availability of another service, which is what you could do as well in this scenario. Check out [Dockerize](https://github.com/jwilder/dockerize#waiting-for-other-dependencies) for a tool that does this out of the box.

As for Kubernetes, I am able to provide health-probes. At the moment, the pod will simply crash and be restarted, when the MongoDB is not available. So it kinda-works, but could be done a lot better IMHO.

**Comment by zasca** [comment]
[healthcheck](https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck) option does possible to wait dependent service:
```yaml
version: "2.1"
services:
  db:
    image: mongo
    volumes:
      - /tmp/rocket.chat/mongodb/runtime/db:/data/db
      - /tmp/rocket.chat/mongodb/dump:/dump
    command: mongod --smallfiles
  app:
    image: rocketchat/rocket.chat:latest
    environment:
      - MONGO_URL=mongodb://db:27017/rocketchat
      - ROOT_URL=https://chat.example.com
      - Accounts_UseDNSDomainCheck=True
    links:
      - db:db
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD-SHELL", "nc", "-z", "127.0.0.1 27017"]
      interval: 5s
      timeout: 1s
      retries: 2
```
