### ISSUE TITLE
 [Feature-Request] Print role in web client compact mode

### ISSUE THREAD

**Issue by nORKy54** [RocketChat/Rocket.Chat#7344]
It could be cool to print users roles when client is set to compact mode.

**Comment by lucasvanhalst** [comment]
You can do this yourself by adding this to the custom CSS:

```css
.compact .message .info .role-tag{
  display: inline;
}
```
