### ISSUE TITLE
Avatar migration still not working properly

### ISSUE THREAD

**Issue by lucasvanhalst** [RocketChat/Rocket.Chat#7385]
The improved avatar migration (#7352) still isn't working properly, and the error messages aren't really saying much. See the log here: https://pastebin.com/kN7F0Npz
Those avatars are currently stored in the database so I assume it's trying to migrate them to place them on disk but it's not working. I'm using the docker image from dockerhub if that makes a difference. The migration is also marked as being executed successfully while it's clearly not.

Rocket.Chat Version: 010a60ac7d1e550e0323c037b7006f7336821600
Running Instances: 1
DB Replicaset OpLog: true
Node Version: 4.6

docker-compose.yml:

```yaml
services:
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./data/runtime/db:/data/db
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
  rocketchat:
    image: rocketchat/rocket.chat:develop
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=https://example.com
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - DDP_DEFAULT_CONNECTION_URL=https://example.com
    ports:
      - 3000:3000
    depends_on:
      - mongo
```

**Comment by MartinSchoeler** [comment]
Possibly related to #7172

**Comment by khobbits** [comment]
I'm using the docker rocketchat image, and and i just had a failed migration.
I tried to rerun the migration by lowering the migration version in the db, but it skipped it saying the migration had already ran.

Newly uploaded avatars appear to work, but none of the old ones do.

My log file looked similar to the above one.

My avatar storage was gridfs, my upload storage s3.

**Comment by geekgonecrazy** [comment]
@lucasvanhalst / @khobbits had you guys tried any release candidate prior to rc.3 ?  If so your migrations are in a partially functioning state.  Please see #7172 where trying to walk through and get instances stuck repaired.

**Comment by khobbits** [comment]
No, no rc builds here. Upgraded from .56 to .57.
I'll look though that thread tomorrow.

**Comment by KervyN** [comment]
We don't use docker and hat 5 instances set up on a single 6 core server.
After upgrading from 0.56.0 to 0.57.0 we encountered the problem that people are not able to login via LDAP when the avatars will be synced. We disabled the avatar sync but now some, not all, avatars wen't missing.

In version 0.56.0 we had the problem that avatar went missing random too. We just clean the the avatarchunks from the database (db.avatars.chunks.remove({})) and resynced.
Now the avatars seem to be in another collection (db.rocketchat_avatars) with only 79 entires (we got 104 user total).

**Comment by sampaiodiego** [comment]
guys we just released `0.57.1` which should fix any avatar migration issue. 

if you were using file system as your avatar storage previous the update, you'll need to set a new environmente variable on first restart to be able to fix the issue. set an env var: `AVATARS_PATH` with the path used for avatar storage.

**Comment by KervyN** [comment]
Does anyone know what will happen if multiple instances have different versions?

**Comment by khobbits** [comment]
I can confirm that upgrading from 0.57.0 to 0.57.1 does fix my avatars.
(after previously having a broken 0.56.0 -> 0.57.0 migration using gridfs->s3)

**Comment by lucasvanhalst** [comment]
I can also confirm 0.57.1 sort off works, but not completely. I have 58 users, it migrated 48 avatars. Those remaining 10 users now have a blank avatar.
The migration also ignored the AVATARS_PATH parameter and uploaded the files in the folder used for uploads instead.

**Comment by TheReal1604** [comment]
@sampaiodiego 0.57.1 had also resolved my issues with migrating avatars. But its @lucasvanhalst mentioned, 2 of 12 users are now missing their avatar. There are no errors in the log after first start of the instance and running the migration.

**Comment by TheReal1604** [comment]
@sampaiodiego upgraded another env, it seems that there is an issue with jpegs?

```
2017-07-11T07:09:02.750535783Z { [Error: Command failed: convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
2017-07-11T07:09:02.750535783Z convert: no images defined `jpeg:/tmp/ufs/EdcrMCcim46yB9L5v' @ error/convert.c/ConvertImageCommand/3210.
2017-07-11T07:09:02.750535783Z ] code: 1, signal: null }

```

**Comment by sampaiodiego** [comment]
@TheReal1604 are you getting this on regular uploads or just during the migration?

**Comment by TheReal1604** [comment]
Doesn't tested uploads, this one was during the migration. @sampaiodiego

**Comment by herste** [comment]
we have a fresh install of 0.57.1 and the login problem persists - meaning: as soon as we have the avatar sync option turned on, users cannot log in. users that are already logged in get all avatars displayed as they are stored in the LDAP directory. But logging out such a client and trying to re-login fails.
From the logs:

LDAPSync ➔ info Syncing user avatar  

After that, no more info on this login process. 

Any ideas on that?

**Comment by sampaiodiego** [comment]
@herste please see #7472

**Comment by sampaiodiego** [comment]
@TheReal1604 which was the avatar file storage and the file upload storage?

**Comment by danpospisil** [comment]
@sampaiodiego @TheReal1604 - we have the same problem while upgrading from 0.56.0 to 0.57.1 - we see the same errors like for some users
`Command failed: convert: no decode delegate for this image format`
We use GridFS

I have reverted back to 0.56.0 until this is solved.

**Comment by rodrigok** [comment]
@danpospisil The problem seams to be related with your imagemagick

Which OS are you using?

Can you run `identify -list format` and check if JPEG is in the list?

**Comment by danpospisil** [comment]
@rodrigok - I am using your Docker image for running Rocket.Chat and I see JPEG there:
```
     JPEG* JPEG      rw-   Joint Photographic Experts Group JFIF format (62)
      JPG* JPEG      rw-   Joint Photographic Experts Group JFIF format (62)
```

**Comment by geekgonecrazy** [comment]
@Horgix please try 0.57.2 as it contains an additional bug fix specifically for avatars

**Comment by Horgix** [comment]
@geekgonecrazy : just updated to `0.57.2`, and it looks like it actually made it worse:

```
{"line":"147","file":"rocketchat_migrations.js","message":"Migrations: Not migrating, already at version 99","time":{"$date":1500965564043},"level":"info"}
```

So nothing has been migrated anyway, but now it's not even possible to update avatars:

```
 [Error: FileNotFound: no file with id yG2Q9ZmgvFmF4yz64 found]
 ufs: cannot write file "yG2Q9ZmgvFmF4yz64" (EACCES: permission denied, open '/yG2Q9ZmgvFmF4yz64') { [Error: EACCES: permission denied, open '/yG2Q9ZmgvFmF4yz64']
   errno: -13,
   code: 'EACCES',
   syscall: 'open',
   path: '/yG2Q9ZmgvFmF4yz64' }
 ufs: cannot delete temp file "/tmp/ufs/yG2Q9ZmgvFmF4yz64" (ENOENT: no such file or directory, unlink '/tmp/ufs/yG2Q9ZmgvFmF4yz64')
```

No idea why it's not trying to look for files directly in `/`, but it didn't do that before and I have trouble understanding why user avatars would ever be stored in the root directory

**Comment by geekgonecrazy** [comment]
@sampaiodiego @rodrigok you guys have ideas here?

**Comment by rodrigok** [comment]
@Horgix are you using filesystem to store avatars? Can you show me the configuration?

**Comment by Horgix** [comment]
@rodrigok yes I am!

I'm using the official Docker image with the default configuration that is provided inside it. For reference, here is the `docker-compose` part that I'm using to run the container:

```
services:
  rocketchat:
    image:          rocketchat/rocket.chat:0.57.2
    restart:        unless-stopped
    volumes:
      - /srv/docker_volumes/rocketchat-uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=<my_root_url>
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    depends_on:
      - mongo
    labels:
      traefik.docker.network: "traefik_default"
      traefik.port: "3000"
      traefik.backend: "rocketchat"
      traefik.frontend.rule: "Host:<my_root_url>"
    networks:
      - default
      - traefik
```
