### ISSUE TITLE
Desktop notifications not working between instances

### ISSUE THREAD

**Issue by N4IR0** [RocketChat/Rocket.Chat#7401]
Rocket.Chat Version: 0.57.0
Running Instances: 3
DB Replicaset OpLog: enabled
Node Version: v4.8.1

Desktop notifications are not working, if a user is currently on another instance than me. When a user is on the same instance the desktop notification is working without issues.

We are using three instances on different locations. All instances are shown with status 'waiting' on the admin page, also each instance is only reachable through https.

Our setup:
![github-graph-rocketchat](https://user-images.githubusercontent.com/7635858/27826106-2f1dfada-60b2-11e7-828b-a66a3df47acc.png)

Docker-Compose file for each instance:
```
version: '3'

services:
  rocketchat:
    restart: always
    image: rocketchat/rocket.chat:0.57.0
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=443
      - INSTANCE_IP=<EXTERNAL IP>
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - ROOT_URL=https://<MAIN DOMAIN>
      - MONGO_URL=mongodb://user:password@node1:27017,node2:27017,node3:27017/rocketchat?ssl=true&replicaSet=rs0&authSource=admin
      - MONGO_OPLOG_URL=mongodb://user:password@<MONGODB ON SAME HOST>:27017/local?ssl=true&authSource=admin
    ports:
      - "127.0.0.1:3000:443"
    logging:
      driver: syslog
      options:
        syslog-facility: daemon
```
