### ISSUE TITLE
File upload extremely slow with multiple instances

### ISSUE THREAD

**Issue by Elethiomel** [RocketChat/Rocket.Chat#7524]
> Rocket.Chat Version: 0.57.2
> Running Instances: 3
> DB Replicaset OpLog: Enabled
> Node Version: v4.8.2

Since upgrading today from 0.57.2 from 0.56 I'm experiencing extremely slow file uploads. Files are taking minutes to upload instead of being nearly instantaneous.

The file seems to upload very slowly in 16k chunks to /tmp/ufs. I can see things like this in /tmp/ufs

`-rw-r--r--` 1 root root 16384 Jul 18 17:51 72j4eMfBmzJFDeeCf

Then some time later....

`-rw-r--r-- 1 root root 32768 Jul 18 17:55 72j4eMfBmzJFDeeCf`

In order to make sure the backend being uploaded to wasn't affecting things, I moved from s3 to a local filestore (in reality a glusterfs filesystem shared between the cluster). It made no distance. When files eventually made it in full to /tmp/ufs they upload to go to s3 or local filestore in a second.

**Comment by localguru** [comment]
Have you tested it with only one running instance?

**Comment by Elethiomel** [comment]
@localguru : Great idea!

Moving to one instance gives me file uploads in a second or two. Moving back to three instances breaks uploads again. 

Any idea what might have changed between 0.56.0 and 0.57.2 to cause this behaviour?

**Comment by Elethiomel** [comment]
I spoke too soon. 2 instances causes slow speeds too. Perhap I didn't wait long enough for the second instance to join when I did my last test. After a minute or so it became as slow as three instances.

**Comment by localguru** [comment]
Seems to be a problem between the nodes then. I don't run multi nodes, just one, because there to many issues open regarding multiple nodes, e.g. like notification problems.

**Comment by localguru** [comment]
may be similar to #7485

**Comment by geekgonecrazy** [comment]
So this is caused by #7304 basically if the post that uploads the file hits another instance then the one you are connected to.. it proxies the request to the instance you are connected to.

**Comment by Elethiomel** [comment]
@geekgonecrazy I could have sworn that I had stickiness enabled on my load balancer, but it turns out that I didn't I'm guessing that enabling it would fix this? Or is it a case that rocketchat communicates through websockets for most things and the plain HTTP post is therefore a different session and could still end up elsewhere?

**Comment by geekgonecrazy** [comment]
sticky sessions will prevent the proxy from needing to happen.  Depending on your proxy the websocket and http post should be treated as same session

**Comment by salamachinas** [comment]
* Version of Rocket.Chat Server: 0.57.3
* Deployment Method: docker
* Number of Running Instances: 4
* DB Replicaset Oplog: Yes
* Node Version: 4.8.2


Upload slow or don't working at all with more than one instance.

Error from logs
```
rocketchat_3   | Exception in callback of async function: Error: getaddrinfo ENOTFOUND undefined undefined:3000
rocketchat_3   |   at errnoException (dns.js:27:10)
rocketchat_3   |   at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
rocketchat_3   | 
```

**Comment by geekgonecrazy** [comment]
@salamachinas it sounds like your instances are not able to talk to each other.  Are you using INSTANCE_IP env variable with your containers?

**Comment by rasos** [comment]
Very slow uploads are also observed with just one instance, see also #7857  
Chunks of 100k arrive in a temporary file in /tmp/ufs .

**Comment by ledainam** [comment]
i have same issue with version 0.59.3
when i use multiple instance, upload from mobile app extreme slow and must choose file more than 2 times, upload can start. 
if i used only one instance, it worked fine.

**Comment by kajisaap** [comment]
```YAML
version: '2'

services:
  rocketchat1:
    image: rocketchat/rocket.chat:0.64.2
    restart: unless-stopped
    volumes:
      - ../shared/uploads:/var/snap/rocketchat-server/common/uploads
    environment:
      - INSTANCE_IP=172.17.43.194
      - PORT=3333
      - ROOT_URL=https://rocket.example.com
      - MONGO_URL=mongodb://mongo1:27017/parties
    ports:
      - 3333:3333

  rocketchat2:
    image: rocketchat/rocket.chat:0.64.2
    restart: unless-stopped
    volumes:
      - ../shared/uploads:/var/snap/rocketchat-server/common/uploads
    environment:
      - INSTANCE_IP=172.17.43.194
      - PORT=4444
      - ROOT_URL=https://rocket.example.com
      - MONGO_URL=mongodb://mongo1:27017/parties
    ports:
      - 4444:4444

  rocketchat3:
    image: rocketchat/rocket.chat:0.64.2
    restart: unless-stopped
    volumes:
      - ../shared/uploads:/var/snap/rocketchat-server/common/uploads
    environment:
      - INSTANCE_IP=172.17.43.194
      - PORT=5555
      - ROOT_URL=https://rocket.example.com
      - MONGO_URL=mongodb://mongo1:27017/parties
    ports:
      - 5555:5555
```

We have 3000+ users with roughly 300-500 users online. All the rocket.chat instances are running in single server and the spec is 16 GB of RAM with 4 cores inside AWS VPC. We have nginx proxing to the rocketchat ports.


We have frequent problems with rocket.chat 
- not responding timely, 
- message not being sent, 
- frozen response,
- uploads are not working. 
- .....very slow

We know replica-set would help but anything besides that we could be missing or points that might help our cases.

Much appreciated.
