### ISSUE TITLE
Docker instance can't resolve socket

### ISSUE THREAD

**Issue by pokapow** [RocketChat/Rocket.Chat#7737]
I'm using docker with last rocket chat official image on debian 8.
I'm using nginx as a reverse proxy to access the container listened port.

This is how I install rocket chat: 
`docker run --name db -d mongo:3.0 --smallfiles`
`docker run --name chat_exp -p 10040:3000 --env ROOT_URL=https://chat.exemple.com --link db -d rocket.chat`

This is my nginx configuration for rocket chat:
```

upstream chat.exemple.com {
   server       127.0.0.1:10040;
}

server {
    listen 80;
    server_name     chat.exemple.com;

    location / {
        proxy_pass http://chat.exemple.com;
    }

    access_log  /var/log/nginx/chat_access.log;
    error_log  /var/log/nginx/chat_error.log;
 }
```

When I try to connect to chat.exemple.com, I have this page:
[Link to what I see](http://hpics.li/d2173b9)

And that it... Firefox tell me that:
[Firefox debug](http://hpics.li/74c25cd)

At the begining I thought it was a problem of connexion between rocket chat and the mongo db, but in fact, it's not. It's a websocket problem, but I don't know wich one and I didn't found more information on internet...

**Comment by pokapow** [comment]
I got exactly the same issue with a docker compose:

```
db:
  image: mongo
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://chat.exemple.com
    - Accounts_UseDNSDomainCheck=True
  links:
    - db:db
  ports:
    - 10040:3000

hubot:
  image: rocketchat/hubot-rocketchat:v0.1.4
  environment:
    - ROCKETCHAT_URL=https://chat.exemple.com
    - ROCKETCHAT_ROOM=GENERAL
    - ROCKETCHAT_USER=user
    - ROCKETCHAT_PASSWORD=passw
    - BOT_NAME=bot
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings
  links:
    - rocketchat:rocketchat
# this is used to expose the hubot port for notifications on the host on port 3001, e.g. for hubot-jenkins-notifier
  ports:
    - 3001:8080
```
