### ISSUE TITLE
[v0.58.4] Specified HTTPS URLs don't embed

### ISSUE THREAD

**Issue by furukawa3** [RocketChat/Rocket.Chat#8642]
### Description:

When I post a URLs in channel for Rocket.chat which is deployed by docker-compose file, the URLs don't embed at all incase of **https**

### Server Setup Information:

* Version of Rocket.Chat Server: v0.58.4
* Operating System: Linux
* Deployment Method(snap/docker/tar/etc): docker (used docker-compose.yml)
* Number of Running Instances: 1
* DB Replicaset Oplog: Disabled
* Node Version: v4.8.4

### Steps to Reproduce:

1. Prepare following docker-compose.yml

 ```yml
version: '2'
services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongo
    environment:
      - ROOT_URL=http://hogehoge.com
     ports:
      - 3000:3000
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
     - ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
  mongo-init-replica:
    image: mongo:latest
    command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
    depends_on:
      - mongo
 ```
2.  Execute following command:

 ```bash
sudo docker-compose -p my-rocket up -d
 ```
3. Access rocketchat and post some URLs

### Expected behavior:

Specified URLs are embedded.

### Actual behavior:

No embedded

### Relevant logs:

No error logs exist.
