### ISSUE TITLE
Export docker Rocket.chat to new systeme

### ISSUE THREAD

**Issue by pokapow** [RocketChat/Rocket.Chat#8878]
I have some issue when I try to import the backup I made from my docker install of rocket.chat to new systeme.
I have all mount folders and a docker commit of the mongodb container.
So I made a docker import from de mongo commit, put this new image of my old mongo container to my docker-compose.yml like this:

```
db:
  image: rocket_chat_backup
  volumes:
    - ./data/runtime/db:/data/db
    - ./data/dump:/dump
  command: mongod --smallfiles
  restart: always

rocketchat:
  image: rocketchat/rocket.chat:latest
  environment:
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=https://chat.exemple.com
    - Accounts_UseDNSDomainCheck=True
  links:
    - db:db
  ports:
    - 10040:3000
#    - 6667:6667
  restart: always

hubot:
  image: rocketchat/hubot-rocketchat:v0.1.4
  environment:
    - ROCKETCHAT_URL=https://chat.exemple.com
    - ROCKETCHAT_ROOM=GENERAL
    - ROCKETCHAT_USER=user
    - ROCKETCHAT_PASSWORD=pwd
    - BOT_NAME=bot
    - EXTERNAL_SCRIPTS=hubot-help,hubot-seen,hubot-links,hubot-greetings
  links:
    - rocketchat:rocketchat
  ports:
    - 3001:8080
  restart: always
```

But when try to up this compose, I have this error:
`docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"mongo\": executable file not found in $PATH".`

Can somebody explain how to correctly export and import docker container of rocket.chat from old system to new clean system ? I didn't any information for this subject.
