### ISSUE TITLE
Scrollbar in rooms list on Firefox

### ISSUE THREAD

**Issue by crazy-max** [RocketChat/Rocket.Chat#8946]
### Description:

Ugly scrollbar in rooms list on Firefox 57.0

### Server Setup Information:

* Version of Rocket.Chat Server: 0.59.3
* Operating System: Linux 3.16.0-4-amd64
* Deployment Method(snap/docker/tar/etc): Docker
* Number of Running Instances: 1
* DB Replicaset Oplog:
* Node Version: v4.8.4

### Steps to Reproduce:

Go to the main page of Rocket Chat in Firefox browser

### Expected behavior:

Remove scrollbar in rooms list

### Actual behavior:

Ugly scrollbar in rooms list on Firefox 57.0

### Docker config

```yaml
version: '3'

services:
  rocket-chat:
    image: rocketchat/rocket.chat:latest
    container_name: rocket-chat
    networks:
      - rocket_default
    volumes:
      - ./uploads:/app/uploads
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PORT=3000
      - ROOT_URL=https://rocket.example.com
      - MONGO_URL=mongodb://rocket-mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://rocket-mongo:27017/local
      - MAIL_URL=smtp://smtp.email
      - VIRTUAL_HOST=rocket.example.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=rocket.example.com
      - LETSENCRYPT_EMAIL=webmaster@example.com
      - ADMIN_USERNAME=webmaster
      - ADMIN_PASS=
      - ADMIN_EMAIL=webmaster@example.com
    depends_on:
      - rocket-mongo
    ports:
      - 3000:3000
    restart: unless-stopped

  rocket-mongo:
    image: mongo:3.2
    container_name: rocket-mongo
    networks:
      - rocket_default
    volumes:
     - ./data/db:/data/db
     - /etc/localtime:/etc/localtime:ro
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    restart: unless-stopped
```

### Screenshots

![scrollbar](https://user-images.githubusercontent.com/1951866/33230846-1c254dac-d1eb-11e7-9779-81674968ba38.png)

![scrollbar-debug](https://user-images.githubusercontent.com/1951866/33230848-22b46c98-d1eb-11e7-9782-e9fa9356e3b4.png)
