### ISSUE TITLE
docker-compose auto start files not working on ubuntu 16.04

### ISSUE THREAD

**Issue by JhonatanPereira** [RocketChat/Rocket.Chat#9993]
### Description:

I'm unable to auto start RocketChat with docker-compose on Ubuntu 16.04 because it don't use Upstart
There are any plans to update rocketchat_app.conf and rocketchat_mongo.conf to Systemd?

### Server Setup Information:

* Version of Rocket.Chat Server: 0.62.0
* Operating System: Ubuntu 16.04
* Deployment Method(snap/docker/tar/etc): docker-compose

### Steps to Reproduce:

1. Create the rocketchat_app.conf and rocketchat_mongo.conf in /etc/init/ as described in documentation
2. Reboot the system also as described in docs
3. The services won't start because Ubuntu 16.04 don't use Upstart but Systemd

### Expected behavior:

Auto start of mongo, rocketchat and hubot services

### Actual behavior:

They won't start

### Relevant logs:

Not needed

**Comment by bbrauns** [comment]
You don't need systemd to auto restart your container. The docker daemon will take care of starting the services. See https://docs.docker.com/compose/compose-file/#restart for specifying a restart policy within your docker-compose.yml

Example:
```
root@chat:~# cat docker-compose.yml
services:
  app:
    depends_on:
    - mongo
    image: rocket.chat:0.61.0
    restart: always
....
```
